### ISSUE TITLE
Indicate when a refresh is required

### ISSUE THREAD

**Issue by aaronjensen** [shellscape/webpack-plugin-serve#103]
### Feature Use Case

If I don't have HMR set up properly or if I make a change at a top-level module that cannot be reloaded, right now the only indication I get that an HMR was not performed is in the dev console. With the progress bar, I may have come to rely on that to mean that my change was made and be confused if I don't see the change take effect.

### Feature Proposal

Indicate somewhere on the page when an HMR fails. Either turn the progress bar red or show some other indicator that a refresh is required to see changes.

**Comment by shellscape** [comment]
Interesting idea. Right now the status and progress overlays are directly related to the webpack build, rather than what the build's code results in. I don't think we'd want to mix the two, but maybe there's another way to accomplish this.

**Comment by shellscape** [comment]
Going through issues for some summer cleaning. It just dawned on me that you could wrap `console.warn` and inspect for a few messages. This is the file that would warn in that scenario https://github.com/shellscape/webpack-plugin-serve/blob/master/lib/client/hmr.js and you could check for each of those messages in your wrapper or proxy method.

That should get you where you want to be. Given the age of the issue, we're going to close for now. But feel free to keep the discussion going. I'll stay subscribed and will see comments.

**Comment by aaronjensen** [comment]
Thanks for the tip.

For what it's worth, the main reason I continue to choose to use this plugin is developer experience. Knowing when a build is happening is very helpful for learning to trust HMR again. One of the other reasons I've seen folks stop trusting HMR is what I described above--if HMR can't reload because it's not accepted, making the developer know that would give them the opportunity to refresh and/or add an appropriate `module.hot.accept` call, which would improve the experience even more. 

Thanks!

**Comment by shellscape** [comment]
Hm that's interesting reasoning. There might be a case then for adding console warnings and errors related to HMR to the status dialog.

**Comment by PlayMa256** [comment]
Or may i go further?
If we get an error on HMR, why don't we add a full red bar on top? Like: "i'm trying to reload, but i failed"

**Comment by shellscape** [comment]
In theory that's what the red title of the status window and red pulse beacon (in the minimized view) are for. Unobtrusive yet informative.
