### ISSUE TITLE
Add support for node v10.15.1

### ISSUE THREAD

**Issue by blackshadev** [shellscape/webpack-plugin-serve#108]
### Expected Behavior / Situation
That `yarn add webpack-plugin-serve` worked on the latest LTS version without adding an `--ignore-engines` flag. 

### Actual Behavior / Situation
An error with `The engine "node" is incompatible with this module. Expected version ">= 8.0.0 < 9.0.0 || >= 10.0.0 < 10.14.0". Got "10.15.1"`

### Modification Proposal
Change engines check to include everything for 10.15.x and upward. Which includes 10.15.1 which is the current LTS version.

**Comment by PlayMa256** [comment]
Which version are you using? I'm saying that because the latest versions already have it whitelisted on engines:

https://github.com/shellscape/webpack-plugin-serve/blob/c93173b579a66a872b4e00f776099156590afdbf/package.json#L14

**Comment by blackshadev** [comment]
Hi, I am so sorry. 
I forgot to include the `--latest` tag in the  yarn upgrade. and it pulled `0.3.1` for me which didn't have that check you mentioned. When I used the latest flag it pulled `0.6.0` and it worked just fine
