### ISSUE TITLE
Migration from create-react-app

### ISSUE THREAD

**Issue by aaronjensen** [shellscape/webpack-plugin-serve#117]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Hi there, I'm trying to swap out the create-react-app server for webpack-plugin-serve and hit the 404 issue: `https://github.com/shellscape/webpack-plugin-serve/blob/master/.github/FAQ.md#what-does-the-not-found--404-error-mean`. I was able to get around that, but now I'm hitting another issue:

```
react-dom.development.js:2490 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at react-dom.development.js:2490
    at Object.../node_modules/react-dom/cjs/react-dom.development.js (react-dom.development.js:22346)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.../node_modules/react-dom/index.js (index.js:36)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.../node_modules/react-hot-loader/dist/react-hot-loader.development.js (react-hot-loader.development.js:17)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
```

I'll probably be able to sort through it all, but having a step-by-step guide of porting from create-react-app would be really helpful to me and probably others. It may even lead to further adoption!

### Your Proposal for Changes

Add a guide for adding webpack-plugin-serve to an ejected create-react-app

**Comment by PlayMa256** [comment]
Hi, can you share what you have done so far? So we can check what is wrong? This error is not related to this plugin, as far as I can see.

**Comment by aaronjensen** [comment]
Sure:

<details>
<summary>webpack.config.js diff</summary>

```diff
diff --git a/client/config/webpack.config.js b/client/config/webpack.config.js
index 426617a..0f57934 100644
--- a/client/config/webpack.config.js
+++ b/client/config/webpack.config.js
@@ -19,10 +19,28 @@ const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeM
 const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin')
 const getCSSModuleLocalIdent = require('react-dev-utils/getCSSModuleLocalIdent')
 const paths = require('./paths')
-const getClientEnvironment = require('./env')
 const ModuleNotFoundPlugin = require('react-dev-utils/ModuleNotFoundPlugin')
 const ForkTsCheckerWebpackPlugin = require('react-dev-utils/ForkTsCheckerWebpackPlugin')
 const typescriptFormatter = require('react-dev-utils/typescriptFormatter')
+const { WebpackPluginServe: Serve } = require('webpack-plugin-serve')
+const argv = require('webpack-nano/argv')
+
+const watch = !!argv.watch
+
+if (watch) {
+  // Do this as the first thing so that any code reading it knows the right env.
+  process.env.BABEL_ENV = 'development'
+  process.env.NODE_ENV = 'development'
+
+  // Makes the script crash on unhandled rejections instead of silently
+  // ignoring them. In the future, promise rejections that are not handled will
+  // terminate the Node.js process with a non-zero exit code.
+  process.on('unhandledRejection', err => {
+    throw err
+  })
+}
+
+const getClientEnvironment = require('./env')
 
 // Source maps are resource heavy and can cause out of memory issue for large source files.
 const shouldUseSourceMap = process.env.GENERATE_SOURCEMAP !== 'false'
@@ -42,7 +60,8 @@ const sassModuleRegex = /\.module\.(scss|sass)$/
 // This is the production and development configuration.
 // It is focused on developer experience, fast rebuilds, and a minimal bundle.
 module.exports = function(webpackEnv) {
-  const isEnvDevelopment = webpackEnv === 'development'
+  const isEnvDevelopment =
+    webpackEnv === 'development' || process.env.NODE_ENV === 'development'
   const isEnvProduction = webpackEnv === 'production'
 
   // Webpack uses `publicPath` to determine where the app is being served from.
@@ -124,23 +143,9 @@ module.exports = function(webpackEnv) {
     // These are the "entry points" to our application.
     // This means they will be the "root" imports that are included in JS bundle.
     entry: [
-      // Include an alternative client for WebpackDevServer. A client's job is to
-      // connect to WebpackDevServer by a socket and get notified about changes.
-      // When you save a file, the client will either apply hot updates (in case
-      // of CSS changes), or refresh the page (in case of JS changes). When you
-      // make a syntax error, this client will display a syntax error overlay.
-      // Note: instead of the default WebpackDevServer client, we use a custom one
-      // to bring better experience for Create React App users. You can replace
-      // the line below with these two lines if you prefer the stock client:
-      // require.resolve('webpack-dev-server/client') + '?/',
-      // require.resolve('webpack/hot/dev-server'),
-      isEnvDevelopment &&
-        require.resolve('react-dev-utils/webpackHotDevClient'),
       // Finally, this is your app's code:
       paths.appIndexJs,
-      // We include the app code last so that if there is a runtime error during
-      // initialization, it doesn't blow up the WebpackDevServer client, and
-      // changing JS code would still trigger a refresh.
+      isEnvDevelopment && 'webpack-plugin-serve/client',
     ].filter(Boolean),
     output: {
       // The build folder.
@@ -509,8 +514,6 @@ module.exports = function(webpackEnv) {
       // during a production build.
       // Otherwise React will be compiled in the very slow development mode.
       new webpack.DefinePlugin(env.stringified),
-      // This is necessary to emit hot updates (currently CSS only):
-      isEnvDevelopment && new webpack.HotModuleReplacementPlugin(),
       // Watcher doesn't work well if you mistype casing in a path so we use
       // a plugin that prints an error when you attempt to do this.
       // See https://github.com/facebook/create-react-app/issues/240
@@ -565,7 +568,7 @@ module.exports = function(webpackEnv) {
           }),
           async: isEnvDevelopment,
           useTypescriptIncrementalApi: true,
-          checkSyntacticErrors: true,
+          checkSyntacticErrors: false,
           tsconfig: paths.appTsConfig,
           reportFiles: [
             '**',
@@ -576,10 +579,16 @@ module.exports = function(webpackEnv) {
             '!**/src/setupTests.*',
           ],
           watch: paths.appSrc,
-          silent: true,
+          silent: false,
           // The formatter is invoked directly in WebpackDevServerUtils during development
           formatter: isEnvProduction ? typescriptFormatter : undefined,
         }),
+      isEnvDevelopment &&
+        new Serve({
+          historyFallback: true,
+          static: paths.appBuild,
+          port: 3000,
+        }),
     ].filter(Boolean),
     // Some libraries import Node modules but don't use them in the browser.
     // Tell Webpack to provide empty mocks for them so importing them works.
@@ -595,5 +604,6 @@ module.exports = function(webpackEnv) {
     // Turn off performance processing because we utilize
     // our own hints via the FileSizeReporter
     performance: false,
+    watch,
   }
 }
```
</details>

**Comment by aaronjensen** [comment]
The `static: paths.appBuild` was confusing, but it was required to get the index to serve. As a result, wp actually writes files to `dist`, so I'm guessing I'm missing something else.

**Comment by PlayMa256** [comment]
You config is right. If you still using the CRA start file to start your project and you are not using any cli, you shouldn't use. CRA spawns webpack-dev-server under the hook using the node api, you must use webpack node api.

> The static: paths.appBuild was confusing, but it was required to get the index to serve. As a result, wp actually writes files to dist, so I'm guessing I'm missing something else.

Yeah, that do the tricky.

About writing files to disk, that is right. It was a design choice from our side. Writing things to memory created some problems in the past, most of them performance problems (hmr, watch, etc). You did everything correct, you are on the right path.

**Comment by shellscape** [comment]
> As a result, wp actually writes files to dist, so I'm guessing I'm missing something else.

`dist` is the default directory to which webpack writes files, if no `output` property exists in the webpack config. So this line from your config:

```js
output: {
      // The build folder.
      path: isEnvProduction ? paths.appBuild : undefined,
```

is telling webpack that `output: undefined` and to use `dist`.

**Comment by aaronjensen** [comment]
> If you still using the CRA start file to start your project and you are not using any cli, you shouldn't use. CRA spawns webpack-dev-server under the hook using the node api, you must use webpack node api.

Not entirely sure I follow this. I was starting with `wp --watch`, is that correct or should I be using the CRA start file? 



> About writing files to disk, that is right. It was a design choice from our side.

Got it, thanks.

So it seems like the error from react I'm seeing is something else. I have no idea what it could be, so I'll keep digging.

**Comment by PlayMa256** [comment]
> Not entirely sure I follow this. I was starting with wp --watch, is that correct or should I be using the CRA start file?

Yeah, you already answer my question. Keep using `wp --watch` :)

**Comment by aaronjensen** [comment]
Okay, it looks like my issue is with the `react-hot-loader/webpack` loader. If I limit that loader to only run for react-dom, I don't get that error. There's still something different, however, as react-hot-loader is not detecting the patch done by react-hot-loader/webpack.

As far as I can tell, when I'm running with `webpack-plugin-serve` my dependencies load in the wrong order. Specificaslly, react-hot-loader is required and it attempts to require ReactDOM, but there must be a circular dependency somehow, because after the require, ReactDOM is the default object export.

Do you have any idea what could cause webpack-plugin-serve to create a circular dependency that isn't there when I'm not using it?

**Comment by shellscape** [comment]
`webpack-plugin-serve` is just a plugin that spins up a dev server. The only thing that it does for the user is add `HotModuleReplacementPlugin`. Besides that, there's no magic and it doesn't manipulate the build. If your build works when running without the plugin, then it should work when running with the plugin. That probably doesn't help very much, but it's important info. There's nothing special about a build with WPS included in plugins versus not.

**Comment by aaronjensen** [comment]
Okay, thanks. It may be that CRA is doing something different then because there's definitely a difference between the two in my app. From what I can tell, react-dom does not finish evaluating before *something* starts to require `react-hot-loader`, which seems wrong. I'll keep looking.

**Comment by shellscape** [comment]
It may be entirely possible that CRA is injecting or manipulating the build based on environment (dev vs prod) as well. I'm not at all familiar with that, so I couldn't say for certain. I do know that there's an option to "eject" from CRA so that you have full control over the build and such, but I don't know what the ramifications of that would be (sorry, I'm super ignorant about React).

**Comment by aaronjensen** [comment]
Here's a repro with step-by-step commits: https://github.com/aaronjensen/hot-serve-repro

It works until I add `webpack-plugin-serve`

This errors as well:

```
manifest.json:1 GET http://localhost:3000/manifest.json 404 (Not Found)
```

I believe that's because CRA expects me to serve the `public` dir statically, but `webpack-plugin-serve` only works when I specify the build directory as the static path. I'm not sure if there's something I'm supposed to do to have it work and have a public directory.

**Comment by shellscape** [comment]
I'm mobile at the moment and can't inspect your repo, but the `static` option does accept an array. Might be worth trying using both directories for that option, unless of course file paths would conflict.

**Comment by shellscape** [comment]
I'm making some time today/tonight to go through issues and should have the chance to take a look at this.

**Comment by shellscape** [comment]
I got absolutely nowhere with this. @PlayMa256 is this something you can poke at for the repo he provided?

**Comment by PlayMa256** [comment]
From the repo itself there is nothing we can get.
BUT as i was looking through the configs added by CRA when bringing the dev server up, they add the public folder to it's content base.

As the manifesto file is also created inside the public folder, i suppose he only needs to add the public folder to `static` array, then koa will be able to serve those files and when plugin tries to fetch it, it is going to be found.

TL;TR: 
```js
module.exports = {
...
   plugins: [
      new WebpackPluginServer({
		static: [path.resolve('./public'))
	  })
   ]
}
```

**Comment by aaronjensen** [comment]
Thanks, I'll give this a shot next chance I get.

**Comment by shellscape** [comment]
@aaronjensen have you had a chance to circle back to this?

**Comment by aaronjensen** [comment]
@shellscape I haven't, I'm not on that project anymore and I haven't needed to use CRA since. Feel free to close this as there's a workaround as described above and there's hopefully enough information in here should anyone else decide to add webpack-plugin-serve to a CRA app.

**Comment by shellscape** [comment]
Solid, thank you.

**Comment by davidroeca** [comment]
Just migrated an old CRA app to `webpack-plugin-serve` with some success. Not for the faint of heart, though.

I used https://github.com/timarney/react-app-rewired to modify the configuration and had to remove/modify a few plugins it uses--you do have to dig a bit into the configuration. I can try to generalize this approach later, but in the meantime if anyone is trying to tackle this and has issues, feel free to @ me on this thread and I'll try to respond and help when I can.

**Comment by shellscape** [comment]
@davidroeca that would be awesome to have in the docs here.

**Comment by davidroeca** [comment]
@shellscape I'll try to get to it when I have some time, hopefully in the next week or so. I wish this plugin had more community adoption--definitely the best of the bunch. In the meantime, is there a good place to put this? Maybe a recipe?

**Comment by shellscape** [comment]
Yeah a recipe would amazing.
