### ISSUE TITLE
`background-color` not set on `#wps-status-problems pre`

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#121]
### Expected Behavior / Situation
`#wps-status-problems pre` sets the `background-color` to be the same as `#wps-status`.

### Actual Behavior / Situation
`#wps-status-problems pre` doesn't set the `background-color`  to be the same as `#wps-status`.

### Modification Proposal

Bit of an odd one, but I'm in a situation where the project I'm working on has unchangeable css, which means `pre` tags are being targeted to have their `background-color` set to a white.

This makes it nearly impossible to read messages from `webpack-plugin-serve` when developing.

If `#wps-status-problems pre` included the `background-color` (like it already does with the `color`), this would fix the problem*.

Let me know if this is something you'd be happy with, and I'll try to handle the PR :)

*: "well enough" - it won't catch all situations, but this is rare enough already that I think this change would stamp out the problem most of the time.

**Comment by shellscape** [comment]
Please do take a crack at it. This is probably about where that change will have to be made: https://github.com/shellscape/webpack-plugin-serve/blob/master/lib/client/overlays/status.js#L108
