### ISSUE TITLE
"compress: true" does not serve compressed assets

### ISSUE THREAD

**Issue by mindpivot** [shellscape/webpack-plugin-serve#123]
- Webpack Version: 4.29.6
- Operating System (or Browser): macOS Mojave 10.14.4, Chrome 73
- Node Version: 10.15.3
- webpack-plugin-serve Version: 0.7.4

### How Do We Reproduce?

set "compress: true" in plugin configuration object

### Expected Behavior
served assets to come down gzipped

### Actual Behavior
no compression observed

**Comment by PlayMa256** [comment]
That is quite interesting... everything is set correctly. I'm going to investigate it. No idea what could be causing it.

**Comment by mindpivot** [comment]
sorry, i should have posted my full configuration...

```
new Serve({
	hmr: true,
	open: true,
	compress: true,
	port: 9000,
	// FOR HTTPS on MAC use this as a guide: https://medium.freecodecamp.org/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec
	// when you have a valid key/crt pair, uncomment host and https properties
	host: 'localhost',
	https: {
		key: fs.readFileSync('webpack/dev-server-certs/server.key'),
		cert: fs.readFileSync('webpack/dev-server-certs/server.crt'),
	},
	status: true,
	progress: false,
	status: false,
	middleware: (app, builtins) => {

		const koaStaticOpts = {
			extensions: ['.html', '.htm']
		};
		builtins.static([
			path.join(ROOT_DIR, 'stub'),
			path.join(ROOT_DIR, 'dist'),
			path.resolve(ROOT_DIR, '..', 'main/content/jcr_root')
		], koaStaticOpts)

		app.use(builtins.proxy('/content', _.merge({}, proxyOptions, {
			target: 'https://www.domainbeingproxiedto.com'
		})));

		app.use(builtins.proxy('/bsro/services', _.merge({}. proxyOptions, {
			target: 'https://ix-dev.domainbeingproxiedto.com',
			changeOrigin: true
		})));

		app.use(router.get('/account/*', (ctx) => {
			ctx.body = fs.readFileSync(path.resolve(__dirname, '..', 'dist/account/index.html'), { encoding: 'utf-8' });
		}));

	}
})
```

**Comment by shellscape** [comment]
I should have some time today to look at this. FWIW here's the code which applies `koa-compress` https://github.com/shellscape/webpack-plugin-serve/blob/803938ff66c1b0bade4c9ffbd337cc3e4dae1c75/lib/middleware.js#L84-L89

**Comment by shellscape** [comment]
So using the `test/fixtures/simple` config, I added `compress: true` to the options and ran `npm run dev`, which spins up the server using that config. Here's the result that I got:

![Imgur](https://i.imgur.com/eW036JS.png)

And that's as expected.

So I'm gonna take a stab in the dark and say that it's probably the proxying causing the issue. It might be worth the shot to call `builtins.compress` as the last thing in the `middleware` option function. `builtins.compress({})` should do it. If you need to explore options for that, those are [here](https://www.npmjs.com/package/koa-compress#options).

**Comment by mindpivot** [comment]
thanks for looking into this @shellscape! I tried commenting out the proxy setup and the `app.use(router...)` call to see if that was the cause to no avail.

this is definitely strange b/c I distinctly remember when I first started using WPS the compression was working great. I've upgraded to version 0.8.0 and am still seeing the same behavior.

I tried stripping out the SSL config, host declaration, all middleware (except the static i need to serve the JS files) and took it down to barebones and nothing is getting the gzip compression

I'm at a loss, usually i'm pretty good about tracking these things down but i can't even stumble upon a working state to use as reference at this point

**Comment by shellscape** [comment]
It might be a function of `static` being called before `compress`. The workflow in `lib/server.js` has `compress` being called before `static`. It's worth attempting a call to `builtins.compress` before, and alternatively, after `builtins.static`.

**Comment by mindpivot** [comment]
that was exactly the problem. I moved my static call down to the bottom of the entire middleware function and everything works! well done @shellscape, well done!

**Comment by shellscape** [comment]
Awesome. We'll add a note to the docs about that.
