### ISSUE TITLE
Localhost replaced with 127.0.0.1

### ISSUE THREAD

**Issue by PeterKottas** [shellscape/webpack-plugin-serve#131]
- Webpack Version: 4.30.0
- Operating System (or Browser): Windows - Chrome
- Node Version: v10.13.0
- webpack-plugin-serve Version: 0.8.0

### How Do We Reproduce?

Provide **host** in options with value "localhost" and **open** "true". The browser indeed opens but the host is replaced with 127.0.0.1. I understand it's equivalent in most cases. However, I need this to explicitly say "localhost" as my oauth2 client expects this host to be set to localhost. 

### Expected Behavior
If the host is set to "localhost" in the config, it should be reflected in opened URL as well as console output which also replaces this with 127.0.0.1

### Actual Behavior

It's replaced to 127.0.0.1

**Comment by shellscape** [comment]
Thanks for reporting the issue :beer:

I'll have a look at this as soon as possible. Hopefully today.

**Comment by PeterKottas** [comment]
Thanks man ;)

**Comment by shellscape** [comment]
@PeterKottas it looks like this is an issue at the core of Node itself. Test code:

```js
→ node
> url.format({ address: 'localhost', family: 'IPv4', port: 55555, hostname: '127.0.0.1' })
'127.0.0.1:55555'
```

Node is making that translation, and there doesn't appear to be any options for `url.format` to prevent that. We have to rely on `url.format` so we can assert that we have a well-formed url. A quick look around the web didn't reveal any issues about this, nor any solutions.

**Comment by PeterKottas** [comment]
Thanks for looking into this. I must say I find it weird though. Older version of webpack-serve I am using works as expected. I therefore assume it uses slightly different technology. I guess I'll stick with the old package for now. In fact, HMR didn't work for me either with this new module. I was hoping I could raise an issue but it's a huge project and I don't have time to create anything small and reproducible. I guess this can be closed without resolution as I could technically replace my auth white-list with 127.0.0.1, it's just local env after all.

**Comment by shellscape** [comment]
I'd very much like to look into why HMR isn't working for you - that's the one feature-point that works far and away better than 2.x webpack-server and webpack-dev-server. (I've been demoing the package at ngConf this week to show that off with Angular in particular). So I'm very curious about that. If you raise an issue about that in the future, rest assured we'll be all over it.

With regard to the older webpack-server version; yes your observation there is correct about the open address - the host name and open url was manually constructed (you can see that being done [here](https://github.com/shellscape/webpack-serve/blob/bd25174bf9484b1c1385296295db253c391cfafa/lib/server.js#L16)). Unfortunately, when treating IPv6 as a first-class citizen, that caused more problems than it solved. So we went the route of letting the system tell us what the URI should be. That is after all, the most reliable method. 

I think to solve this we can do a simple logical check:

```
if options.host is localhost and parsed url host is 12.0.0.1 then
  replace 127.0.0.1 with localhost
```

I'm just curious as to whether or not that will break for folks expecting the localhost IP versus hostname.

**Comment by PeterKottas** [comment]
Your enthusiasm for improving this package is remarkable! Yeah, I've seen people saying this is by far better than alternatives. What I could do is give you a call on skype and run you through the setup. Maybe we'll find the problem together. Otherwise, raising a proper issue is almost impossible because of the complexity (on the screen share, I could just quickly show you around and you could ask in real-time)

Understandably, that's quite uncommon so no big deal if you're not up for it.

TBH, I think at some point, one way or another, I will be forced the upgrade this package and maybe figure things out myself. Maybe by that time, it will just work.

As for this issue, great to see there's a willingness to fix this. I understand the reasons now, moving to ipv6 is for sure a good reason to use proper URL formatting provided by node. 

I think this "replace hack" might be worth it. As long as you can provide host as '127.0.0.1' and it would then set it to '127.0.0.1' while the localhost would work as discussed. Hopefully, even if it breaks anything, people could just swap 'localhost' with '127.0.0.1'. That seems like an easy fix, while at the moment, achieving 'localhost' in URL is impossible.

**Comment by shellscape** [comment]
Turns out that a good night's sleep and fresh pair of eyes does a world of good. My assertion about `url.format` wasn't correct. We were essentially passing bad data to it, due to some dissimilarities between what `url.format` expects and what `server.address()` gives us.

The fix for this is here https://github.com/shellscape/webpack-plugin-serve/pull/132 and awaiting review.

**Comment by PeterKottas** [comment]
Awesome! Cheers man :)
