### ISSUE TITLE
HMR not working.

### ISSUE THREAD

**Issue by PeterKottas** [shellscape/webpack-plugin-serve#135]
- Webpack Version: 4.30.0
- Operating System (or Browser): Windows - Chrome
- Node Version: v10.13.0
- webpack-plugin-serve Version: 0.10.0

### How Do We Reproduce?

As discussed in https://github.com/shellscape/webpack-plugin-serve/issues/131, this is kind of hard to reproduce on a simple example. I will do my best to explain everything in the following lines.

I am using react hot loader 4.8.4 along with "@hot-loader/react-dom": "^16.8.6". 
Hot loader is configured using old api mentioned here https://github.com/gaearon/react-hot-loader#appcontainer.

webpack-plugin-serve is configured with webpack config:
```
...
   entry: {
      site: "./ClientApp/boot-client.tsx",
      'wpsc': 'webpack-plugin-serve/client'
    },
...
   plugins: [
      new Serve({
         port: 54766,
         static: "build",
         open: true,
         host: 'localhost',
         hmr: true,
         historyFallback: true
      })
   ],
   watch: true,
...
```

The rest is fairly exotic, main features it supports/uses are typescript, WebAppWebpackPlugin, MiniCssExtractPlugin, scss, multiple environments, TerserPlugin, SitemapPlugin, RobotstxtPlugin ...
The whole thing is around 400 lines, I am happy to post it here if need be but for now, I've just provided 'important' parts.

### Expected Behavior
HMR should work. 

### Actual Behavior
HRM appears to work, ws connections is there, even progress reporting works (although it waits for the typechecking (via ForkTsCheckerWebpackPlugin) to finish instead of build). But the module is not replaced. This is output I get:

```
⬡ wps: Hot Module Replacement is active
wpsc.0fdd23f2653fa4b0f30a.js:1005 
⬡ wps: WebSocket connected 
hmr.js:64 
⬡ wps: Build 2246e45 replaced:
 []
```
Notice the empty array at the end. I assume this is where the replaced modules should be.

One extra thing I've noticed is the build gets around 50% slower than using old webpack-serve. Not sure why though.

**Comment by PeterKottas** [comment]
To keep things simple, I've even modified ts build to use babel and therefore updated react-hot-loader to use recommended api https://github.com/gaearon/react-hot-loader#getting-started.
Full loader config taken from: https://github.com/gaearon/react-hot-loader#getting-started
Therefore now it's "fairly" standard setup that should IMHO work. Unless I forgot about something :)

**Comment by PeterKottas** [comment]
Okay, first bug spotted. Apparently I need to do 
```
   entry: [
      "./ClientApp/boot-client.tsx",
      'webpack-plugin-serve/client'
    ],
```
instead of
```
   entry: {
      site: "./ClientApp/boot-client.tsx",
      'wpsc': 'webpack-plugin-serve/client'
    },
```
interesting.

```
   entry: {
      site: "./ClientApp/boot-client.tsx",
      'webpack-plugin-serve/client': 'webpack-plugin-serve/client'
    },
```
Doesn't work either.

**Comment by shellscape** [comment]
Good sleuthing! As you discovered, the client entry has to be attached to an existing entry, that way the lib gets added into the code that webpack produces for every regular entry. We might be able to make the documentation clearer on that point.

Looking forward to seeing what else you're able to find. If you get stuck, I'd recommend starting with the react recipe in this repo and bolting on build features from your own config, one at a time, until the problem reveals itself.

**Comment by PeterKottas** [comment]
Managed to get it to work! 
The last problem was using dynamic imports. I just had to make sure the components were exported as hot. But this is obviously not a problem with this lib. Good stuff then! It indeed works well with a bit of following the docs. 

To wrap things up, I would probably make 2 suggestions to make things simple:
1. The docs should mention that object syntax for entry in webpack is not supported. You got to use arrays.
2. This is an actual bug but not a major thing. If using ForkTsCheckerWebpackPlugin, the progress service will not work properly. It continues loading even after the modules are updated and it waits for the TS type-checking to finish.

**Comment by PeterKottas** [comment]
I assume the progress reporting thing is not fixable though as technically webpack is still working and you have no way of knowing if there will be some more updates in the current build. But maybe we can just assume there's only one update per build and cut the loader there?

**Comment by shellscape** [comment]
Great work!

> The docs should mention that object syntax for entry in webpack is not supported. You got to use arrays.

It actually does! It's just a little different. For example:

```js
entry: {
  a: ['thing.js', 'webpack-plugin-serve/client']
}
```

We can make a point to highlight the different entry types and how to integrate the client script. 

> I assume the progress reporting thing is not fixable though as technically webpack is still working

That is correct. We're at the mercy of webpack on that one. That might be a good report to webpack, but not sure how much traction you'll get. 

We'll leave this open as a documentation issue, and when I get the chance I'll get an update in there.

**Comment by PeterKottas** [comment]
Thanks for the info man! Yeah, you're right. Maybe it's just me not reading webpack docs properly. I didn't know you can combine object and array syntax but on a second look, it makes perfect sense. 

I might raise this @ webpack at some point, though this won't be easy.

**Comment by dyardyGIT** [comment]
> The last problem was using dynamic imports. I just had to make sure the components were exported as hot.

Can you explain "The last problem was using dynamic imports. I just had to make sure the components were exported as hot. "? 

I have the same issue, where i see hmr updates but the page is not reflecting those changes.  Idea?

**Comment by PlayMa256** [comment]
@dyardyGIT he was referencing item 2 on react-hot-loader (https://github.com/gaearon/react-hot-loader#getting-started)
