### ISSUE TITLE
middleware > static builtin does not have same usage as koa-static

### ISSUE THREAD

**Issue by agilgur5** [shellscape/webpack-plugin-serve#151]
- Webpack Version: 4.9.1
- Operating System (or Browser): macOS High Sierra 10.13.6
- Node Version: 10.16.0
- webpack-plugin-serve Version: 0.12.0

^Might want to check out how [`nyc` uses `npx envinfo@latest --preset nyc`](https://github.com/istanbuljs/nyc/blame/00c3b3440a5b2ffe11b9c19ae4e08ad2f5b70e33/.github/ISSUE_TEMPLATE.md#L20-L23) in order to get the above table easily from all users reporting issues. 

### How Do We Reproduce?

Any usage of the static middleware, for instance:

```javascript
    // ...

    new WebpackPluginServe({
      middleware: (app, builtins) => {
        app.use(builtins.static('build/'))
      }
    })
```

### Expected Behavior

Per the repro example, that `build/` is served by `koa-static`.

### Actual Behavior

`TypeError: middleware must be a function!` coming from `koa` on the `app.use` line.

In order to get it to work, one must wrap it in a function, changing it to:
```javascript
app.use(() => builtins.static('build/'))
```

This is different behavior than how one would use `koa-static` directly, as that would be:
```javascript
app.use(koaStatic('build/'))
```
I would expect it to work the same given that the documentation says "forwards to [koa-static](https://github.com/koajs/static)" and nothing else, but it does not.

Changing this to work as expected would be a breaking change (according to ComVer at least, debatable if it would be a patch per SemVer), so I did not submit a PR. This might also be the case for other middlewares, but I have not used those yet (`proxy` works as expected, but it is just a koa convert wrapper method).

**Comment by shellscape** [comment]
Thanks for the issue :beer:

So this is more of a documentation issue than anything. You don't actually have to wrap the call to `builtins.static` in a method, nor use `app.use` with that built-in middleware. The reason can be seen here: https://github.com/shellscape/webpack-plugin-serve/blob/b935e8790670bc77adf7be357f6dd65defee7ec6/lib/middleware.js#L127-L133

It's calling app.use for you. This is kind of ambiguous and definitely unclear based on the documentation. In fact, `builtins.proxy` is the _only_ built-in middleware that requires calling `app.use`.

**Comment by agilgur5** [comment]
Uwaaa, that is definitely not how I expected it to work and the inconsistency is really confusing 😖 

The [proxying section](https://github.com/shellscape/webpack-plugin-serve#proxying) is the only place `builtins` are used in the README, and as far as I can tell, it seems like it's also the only recipe to use `builtins` as well. So the only example usage of `builtins` is with `proxy` which is also the only one that's different from the rest 😕

**Comment by shellscape** [comment]
Yeah agreed this isn't ideal. I'll try to put together some better documentation this week.

**Comment by shellscape** [comment]
@agilgur5 I updated the README to point to a built-ins recipe that goes over that in more detail. If you feel that it needs to be more verbose, please let me know how I can improve it. Thanks again for raising the issue.

**Comment by agilgur5** [comment]
Left some comments on the commit itself, but there's a few other things:
- The links to `#middleware` in the README in `#static` and `#proxying` might need to be updated to the new recipe (unless you'd prefer users to read the note in the README before moving to it -- `#static` link should probably still be updated in either case)
- You probably already know this, but `four0four`, `headers`, and `websocket` aren't documented. It's a little bit confusing that the recipe says to use the same options as in the README for these, as it makes you think you missed something.

**Comment by shellscape** [comment]
@agilgur5 I'll see about fixing that up this week. @PlayMa256 any chance you have time to address those comments?

**Comment by PlayMa256** [comment]
Of course I can @shellscape ! Let me open my pc

**Comment by PlayMa256** [comment]
@agilgur5 can you have a look at it aswell? https://github.com/shellscape/webpack-plugin-serve/pull/158
