### ISSUE TITLE
feat: reload button (for when you can't reload i.e electron)

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#155]
### Feature Use Case
I typically turn auto-reload off b/c I like to tweak changes in code while working, and don't want my current app state to go away.

However, it's not always easy to reload: In particular, when working w/ Electron, I have to either click w/ my mouse into the menu, or run `location.reload()` in the console.

The former requires I go into the menu and find the reload item each time - this takes a couple of clicks, requires me to mentally parse the list to find the reload menu item, and actually have the menu enabled in the first place.

The latter requires me to type that command out, and have the dev tools both enabled & opened - if I close the devtools (i.e for space reasons), then I have to re-open it via a few more mouse clicks.

It would be great to have a button I could click to trigger the reload.

### Feature Proposal

A "showReloadButton" option that means when progress gets to `100%` instead of hiding, it shows a button in the center that when pressed reloads the page.

-----

I'm happy to try a PR for this, and don't mind doing this as a separate package like we did for `webpack-serve-overlay` if that's possible, but in particular I really like the idea of having the progress indicator w/ a reload button the center :joy:

**Comment by shellscape** [comment]
Thanks for the suggestion as always @G-Rath. I can see how this would be useful, but have you considered that it could be done pretty easily using a conditional entry in your bundle?

**Comment by G-Rath** [comment]
> it could be done pretty easily using a conditional entry in your bundle

I'm assuming you're meaning `Webpack`'s entry - of which no I'd not considered, as I've not had a decent chance to explore the entry system.

Would you be able to give me some pointers on how I could go about this? (doc links would be fine 😄)

**Comment by shellscape** [comment]
Yeah so in webpack.config.js, like outlined in the README:

```js
const { WebpackPluginServe: Serve } = require('webpack-plugin-serve');
const options = { ... };

module.exports = {
	// an example entry definition
	entry: [
		'app.js',
		'webpack-plugin-serve/client',
                'reload-button.js'
	]
  ...
};
```

See where I added `'reload-button.js'`. That script can just be plain js, and you'll need to flex that basic DOM knowledge. Use `document.addEventListener("DOMContentLoaded", ...);` and add a button with some style and hook it's `click` event handler up to `location.reload()`.

**Comment by G-Rath** [comment]
Ah very cool! I suspected that would be how it worked, but haven't had the time to play around w/ webpack.

I guess that also means I could break it out into it's own package à la `webpack-serve-overlay` (ah, remember those days?): `webpack-plugin-serve-reload-button` 😄 

I'll have a playaround and see what I can come up with. Cheers!

**Comment by shellscape** [comment]
Cool. Thanks for working on that. I'm going to close for now, but ping me if you run into a snag.
