### ISSUE TITLE
Warning - Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by davidroeca** [shellscape/webpack-plugin-serve#157]
- Webpack Version: 4.40.2
- Operating System (or Browser): Linux Mint 19 (Firefox)
- Node Version: 12.10.0
- webpack-plugin-serve Version: 0.12.1

### How Do We Reproduce?
Clone [this repo](https://github.com/davidroeca/wps-issue-157-repro), then run `npm ci` and `npm start`.

Load `localhost:5000` in your browser. 

Then edit `src/logger.js` and update the message within `console.log`. You should see the reproduction in your browser as well as in your webpack watch script.

### Expected Behavior

Hot module replacement to not issue warnings when nothing out of the ordinary is happening

### Actual Behavior

This warning pops up:

`Conflict: Multiple assets emit different content to the same filename <hash>-wps-hmr.json`

![image](https://user-images.githubusercontent.com/6155705/65000519-edb32200-d8b9-11e9-826b-e6acff7efaaf.png)

**Comment by davidroeca** [comment]
Downgrading `webpack-plugin-serve` leads to the same error and I haven't encountered this one before, which makes me think it's an upstream issue, I'm just unclear as to which upstream dependency is the problem.

**Comment by davidroeca** [comment]
Can confirm that this is an issue with `wepback>=4.40.0`. `4.40.0` causes a failure, and `>=4.40.1` emits a warning. The [4.40.1 release](https://github.com/webpack/webpack/releases/tag/v4.40.1) eludes to this check.

**Comment by shellscape** [comment]
Can you put together a `package-lock.json` for `npm` that we can use to reproduce that error? Not a yarn user :)

Are there any steps to reproduce that are needed, or just starting the server displays the error?

**Comment by davidroeca** [comment]
:+1: updated the repo and reproduction instructions to use npm

**Comment by shellscape** [comment]
Thank you. I cloned and ran and was able to confirm the issue. We've been using webpack@4.35.3 internally, and it appears that version 4.40.0 has started to cause this error. I've no idea why as yet, I'll have to investigate that webpack tag to find out more. For the time being, the workaround is to downgrade to webpack@4.39.x

**Comment by shellscape** [comment]
I've created an issue with the webpack project, but I'm not sure how much traction it will get. Please voice your support here: https://github.com/webpack/webpack/issues/9706

**Comment by shellscape** [comment]
I've got a workaround in place but it involves directly manipulating the `stats` object returned from a compilation, and history has taught me (working on webpack-stylish) that doing so can cause headaches later on. It'll be a worst case scenario if the webpack project shoots down that issue.

**Comment by davidroeca** [comment]
Makes sense, hopefully they don’t.

**Comment by davidroeca** [comment]
Looks like the fixes have [been released](https://github.com/webpack/webpack/releases/tag/v4.40.3) and functionality is back to normal

**Comment by shellscape** [comment]
Awesome. Thanks for keeping an eye on this.
