### ISSUE TITLE
Vue Project Not Reloading

### ISSUE THREAD

**Issue by dyardyGIT** [shellscape/webpack-plugin-serve#160]
In short, my browser is not reloading when changes are made the js/vue files.
I am sure it was at one point and am at all as to why it stopped working.

I am building js/vue files in scripts/appVue/changeorder directory and scripts/appVue/changeorderdetails directory.  I am outputting compiled js files to scripts/bundle.  The entry point will be an index.js file within each of these directories.  I am appending the webpack-plug-server/client to the jsEntries.

I did notice with this plugin that it puts recompiled js files on disk (unlike the webpack dev server > this is normal operation?

I can see npm rebuilding the js/vue files in the console **but the browser is not refreshing to reflect changes.**

My webpack.config.js file

```
var path = require('path');
var webpack = require('webpack');
var fs = require('fs');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

const { WebpackPluginServe: Serve } = require('webpack-plugin-serve');
const options = {};

var appBasePath = './Scripts/appVue/';

var jsEntries = {}
// We search for index.js files inside basePath folder and make those as entries
fs.readdirSync(appBasePath).forEach(function(name) {
    var indexFile = appBasePath + name + '/index.js'
    if (fs.existsSync(indexFile)) {
        jsEntries[name] = indexFile
    }
})
jsEntries['webpack-plugin-serve/client'] = 'webpack-plugin-serve/client';

// This is main configuration object.
// Here you write different options and tell Webpack what to do
module.exports = env => {

    var environment = process.env.NODE_ENV || 'development';
    console.log('environment:', environment);
    
    if (process.env.NODE_ENV === 'production') {
        console.log('Welcome to production');
    }

    console.log('--jsEntries--');
    var propValue;
    for (var propName in jsEntries) {
        propValue = jsEntries[propName]

        console.log(propName, propValue);
    }

    return {

        // Path to your entry point. From this file Webpack will begin his work
        entry: jsEntries,

        // Path and filename of your result bundle.
        // Webpack will bundle all JavaScript into this file
        output: {
            path: path.resolve(__dirname, './Scripts/bundle/'),
            publicPath: '/Scripts/bundle/',
            filename: '[name].js'
        },

        resolve: {
            extensions: ['.js', '.vue', '.json'],
            alias: {
                'vue$': 'vue/dist/vue.esm.js',
                '@': path.join(__dirname, appBasePath)
            }
        },

        // Default mode for Webpack is production.
        // Depending on mode Webpack will apply different things
        // on final bundle. 
        mode: environment, //set by mode= on script line
        watch: true,
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /(node_modules)/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }
                },
                // this will apply to both plain `.js` files
                // AND `<script>` blocks in `.vue` files
                {
                    test: /\.js$/,
                    exclude: /(node_modules|bower_components)/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }
                },
                // this will apply to both plain `.css` files
                // AND `<style>` blocks in `.vue` files
                {
                    test: /\.css$/,
                    use: [
                        'vue-style-loader',
                        'css-loader'
                    ]
                },
                {
                    test: /\.vue$/,
                    loader: 'vue-loader',
                    options: {
                        loaders: {}
                        // other vue-loader options go here
                    }
                },
                {
                    test: /\.css$/i,
                    use: ['style-loader', 'css-loader'],
                },
                {
                    test: /\.(eot|svg|ttf|woff|woff2)(\?\S*)?$/,
                    loader: 'file-loader'
                },
                {
                    test: /\.(png|jpe?g|gif|svg)(\?\S*)?$/,
                    loader: 'file-loader',
                    query: {
                        name: '[name].[ext]?[hash]'
                    }
                }
            ]
        },
        plugins: [
            new VueLoaderPlugin(),
            new Serve({
                // note: this value is true by default
                hmr: true,
                static: [path.resolve(__dirname, './Scripts/bundle/')]
            })
        ],
        devtool: 'source-map',
        devServer: {            
            contentBase: path.join(__dirname, 'scripts/bundle'),
            compress: true,            
            hot: true,            
            open: true,
            proxy: {
                //was last using this one
                //port:8080,
                //'*': {
                //    //target: 'http://localhost:5001',
                //    target: 'http://localhost',
                //    changeOrigin: true
                //}
            }
        }
    };
};

```
Is something not quite right here?

**Comment by shellscape** [comment]
Without a full _**minimal**_ reproduction we're unlikely to be able to help you out much just by looking at your config. It also looks like you have some leftovers from a webpack-dev-server implementation. I'd recommend starting with one of our recipes that are known to be functional, and adding onto the recipe config from there. That should reveal where your project is going sideways.

**Comment by dyardyGIT** [comment]
Good perspective.  I am trying the vue sample now.

I am hosting the web application on localhost (**IIS**) would this have an impact on the ability for the page to auto-reload when changes are made in the js/vue?

**Comment by shellscape** [comment]
It shouldn't. If your IIS setup has any modules (I forget what they're called, but basically extensions for IIS) that are blocking WebSocket communication, or the ports that the server is using, or even mutating headers, that might have an impact.

**Comment by dyardyGIT** [comment]
Ok (that was a long standing question I had)

Using the vue recipe, and the webpack.config and package.json within my project I am fighting this one


  ERROR in ./scripts/appvue/changeorder/MyGridComponent.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--0!./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./scripts/appvue/changeorder/MyGridComponent.vue?vue&type=script&lang=js&)
  Module not found: Error: Can't resolve '@babel/runtime/helpers/defineProperty' in 'C:\tfs\IT\CH2Mobile\ODOT\Main\ODOT\ODOT.Web\scripts\appvue\changeorder'
   @ ./scripts/appvue/changeorder/MyGridComponent.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--0!./node_modules/babel-loader/lib??ref--1!./node_modules/vue-loader/lib??vue-loader-options!./scripts/appvue/changeorder/MyGridComponent.vue?vue&type=script&lang=js&) 2:0-68 24:8-23
   @ ./scripts/appvue/changeorder/MyGridComponent.vue?vue&type=script&lang=js&
   @ ./scripts/appvue/changeorder/MyGridComponent.vue
   @ ./scripts/appvue/changeorder/index.js
   @ multi ./scripts/appvue/changeorder/index.js webpack-plugin-serve/client

**Comment by shellscape** [comment]
Not sure on that one. As far as I know the recipe is stable.

**Comment by dyardyGIT** [comment]
I downloaded the recipe and extracted to this dir 
C:\Temp\webpack-plugin-serve-master\recipes\vue

I did have to update node version, and now seeing this 

WebSocket connection to 'ws://[::]:55555/wps' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID

ideas?

**Comment by PlayMa256** [comment]
let me double check (we are both not used to vue). I'll see it!

**Comment by dyardyGIT** [comment]
I am on windows 10, using google chrome, firefox and even edge chromium

**Comment by PlayMa256** [comment]
Oh interesting... this is a problem with windows i suppose, i just proxied my server (linux) to open on windows and i got the same error!

![image](https://user-images.githubusercontent.com/831308/69736065-92e74380-1110-11ea-970c-1f2b067b4596.png) 

Translation: `Firefox could not establish conection with the server ws://[::]:55555/wps`

**Comment by dyardyGIT** [comment]
Seems hard to believe I am the only person on windows and seen this?

**Comment by PlayMa256** [comment]
@dyardyGIT not really, the only thing is most people use either mac or linux for development...

I'm really not sure what could be causing this... @shellscape do you know any peculiarities/incompatibilities that `ws` might have with windows?

**Comment by dyardyGIT** [comment]
I found similar post here and tried 

```
//new Serve({
          //  // note: this value is true by default
          //  hmr: true,
          //  historyFallback: true,
          //  static: [outputPath]
          //})
          new Serve({
            host: "localhost",
            progress: "minimal",
            port: 8080,
          })
```

This configures websocket to communicate on ws://127.0.0.1:8080/wps which solves the above problem on ws://:55555 (obviously on windows you have to tell WS which ip and port to run on)

**Comment by dyardyGIT** [comment]
Okay I am getting closer.  Path question.
I am hosting my site in an application i.e. http://localhost/mysite and the bundle is getting built /mysite/scripts/bundle (as i make changes to js/vue files I see respective changes and *hmr.js files getting created)

I also noticed that for the browser to reload based on the changes the page must have reference to the following client.js file
<script type="text/javascript" src="/Scripts/bundle/webpack-plugin-serve/client.js"></script>

As my site is not at the root, i need this path to be more like 
http://localhost/**MySite**/Scripts/bundle/webpack-plugin-serve/client.js
(or relative with ../ preceding /Scripts (is this possible?)

**Comment by dyardyGIT** [comment]
I believe this can be closed and i have repo on [github](https://github.com/dyardyGIT/WebApplication1---webpack-plugin-serve) as fyi
