### ISSUE TITLE
index.js is not accepted Update propagation (hmr issue)

### ISSUE THREAD

**Issue by dyardyGIT** [shellscape/webpack-plugin-serve#162]
I am using the vue recipe, and when i modify the index.js i get an error like below

```
changeorder.js:476 Uncaught (in promise) Error: Aborted because ./Scripts/app/changeorder/index.js is not accepted
Update propagation: ./Scripts/app/changeorder/index.js -> 0
    at hotApply (changeorder.js:476)
    at replace (hmr.js?797c:60)
```

This error occurs when i modify the test property below..within index.js and expect that HMR will pick up the change.
```

import Vue from 'vue';
import App from './App';

const render = () => {
  const el = document.createElement('div');
  document.body.appendChild(el);

  new Vue({
    el,
      render: h => h(App),
      data() {
          **test:"test"**
      }
  })
}

render()

```

You can see this issue with the simple-small sample in [repo](https://github.com/dyardyGIT/WebApplication1---webpack-plugin-serve)

**Comment by shellscape** [comment]
@dyardyGIT thanks for the issue. Please note in the future that issue templates are _not_ optional and we require everyone to fill the appropriate template out in its entirety.

Vue HMR is still working correctly, so it looks like there's something amiss with your webpack config. Please see the working recipe for Vue here: https://github.com/shellscape/webpack-plugin-serve/tree/master/recipes/vue
