### ISSUE TITLE
stepping into source code help

### ISSUE THREAD

**Issue by dyardyGIT** [shellscape/webpack-plugin-serve#164]
How do I step into vue files? (js seems to show up ok, however you can see here that my vue page has multiple GridDetails.vue?xxxx and they are minimized?

I am using the vue recipe for webpack.config..

ideas?

![2019-12-04_9-14-37](https://user-images.githubusercontent.com/3586830/70149780-d09b1d80-1676-11ea-8bd2-e2150443b2de.png)
![2019-12-04_9-17-07](https://user-images.githubusercontent.com/3586830/70149821-e27cc080-1676-11ea-8299-0bc5eca83ab8.png)

**Comment by shellscape** [comment]
Not really sure that's a question for this module. That's more of a general devtools question for Vue or webpack + Vue isn't it?

**Comment by dyardyGIT** [comment]
I am not sure if it is issue with webpack and how it builds or how the vue files are being served i.e. you can see multiple GridDetails.vue in the above screenshot...is that normal? Where would i put a breakpoint (and the vue files seem to be compressed)

While i recognize may not be bug/issue i was hoping others had some experience as to what should be expected here.
