### ISSUE TITLE
Duplicate Instances of "webpack-plugin-serve/client"

### ISSUE THREAD

**Issue by Twiggeh** [shellscape/webpack-plugin-serve#166]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
![gasdfasertasefsarsdf](https://user-images.githubusercontent.com/23149166/73445260-912d3c80-435a-11ea-9582-54e57a5eea6f.PNG)

Is the same as in the Docs, but I get an error of Duplicate Instances of "webpack-plugin-serve/client" => configuration.entry should not contain the item 'webpack-plugin-serve/client' twice. 

Note: For more information and examples on configuring the entry property, please see the Configuring Entry Points recipe. => Dead Link

### Your Proposal for Changes

Maybe I did something wrong or is the plugin already appended by default ? 
If so the documentation line shouldn't include it :) 

Update the dead link :)

**Comment by PlayMa256** [comment]
If you are using `webpack-serve` it already inserts the entry for you. To insert manually you need to use `webpack-plugin-serve` instead

**Comment by shellscape** [comment]
The documentation is pretty clear on how to use this plugin with webpack and a webpack CLI (such as webpack-nano). It looks like you're trying to use this plugin with webpack-serve, which is incorrect. What you're doing is basically using a development server to add a plugin that starts a development server. You have two choices:

1. Use `webpack-nano` or `webpack-cli` to launch your build with `webpack-plugin-serve` in your plugins
2. Remove `webpack-plugin-serve` and use `webpack-serve` to launch your build

This isn't a shortcoming in our documentation, rather a misunderstanding of the tools available.
