### ISSUE TITLE
error-inject package not in npm registry

### ISSUE THREAD

**Issue by JordanLongstaff** [shellscape/webpack-plugin-serve#167]
- Webpack Version: N/A
- Operating System (or Browser): N/A
- Node Version: 6.13.7
- webpack-plugin-serve Version: Latest

### How Do We Reproduce?
Cannot install webpack-plugin-serve because of a dependency that supposedly does not exist.

### Expected Behavior
webpack-plugin-serve should install just fine.

### Actual Behavior
Console output:
```
error Couldn't find package "error-inject" on the "npm" registry.
```

**Comment by shellscape** [comment]
If this were the case all of our tests would fail. Please provide a repo that reproduces the error and we'll reopen this.

**Comment by JordanLongstaff** [comment]
Well, I tried again today and it worked. So I have no clue and I will stop caring about it. 😕

**Comment by shellscape** [comment]
Was probably a temporary npm hiccup. It's known to happen occasionally.
