### ISSUE TITLE
Refused to connect to WebSocket because it violates CSP directive

### ISSUE THREAD

**Issue by JordanLongstaff** [shellscape/webpack-plugin-serve#168]
- Webpack Version: 4.29.6
- Operating System (or Browser): macOS / Google Chrome
- Node Version: 6.13.7
- webpack-plugin-serve Version: Latest

### How Do We Reproduce?
Browser console spits out an error that it cannot connect to the established WebSocket because of a Content Security Policy violation. My plugin configuration is as follows:
```
plugins.push(
    new WebpackPluginServe({
        client: {
            address: 'localhost:9001',
        },
        historyFallback: true,
        hmr: true,
        ramdisk: true
    }),
);
```

Adding the `historyFallback` and `client` specs were part of previous attempts to fix this. Neither worked.

### Expected Behavior
Supposedly, my web app is supposed to connect to the WebSocket.

### Actual Behavior
Browser console output (partly redacted):
```
ClientSocket.js:44 Refused to connect to 'ws://localhost:9001/wps' because it violates the following Content Security Policy directive: "connect-src ..."
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions). These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to reopen the issue and triage further.

It also looks like you might be trying to develop an extension. If that's the case, you'll have to loosen the CSP for development.
