### ISSUE TITLE
Hot reload extracted CSS file?

### ISSUE THREAD

**Issue by saulfautley** [shellscape/webpack-plugin-serve#169]
I got HMR working with this with very little effort, and it works great! Very similar to Parcel's HMR that I've become accustomed to.

However, I can't seem to get hot reloading working with compiled CSS. I'm using Stylus (`import './index.styl'`) and extracting it with the `MiniCssExtractPlugin` to a separate CSS file.

After reading through docs and recipes it doesn't seem like this isn't currently possible, but I figured I'd ask just to make sure I'm not missing something.

**Comment by shellscape** [comment]
You might want to try using https://github.com/shellscape/webpack-plugin-serve#livereload instead for CSS. I'm not sure (but I don't think) that webpack supports HMR for CSS. But you _can_ tell webpack to watch those files and `liveReload` should reload the page when a new build happens.

**Comment by saulfautley** [comment]
> You might want to try using https://github.com/shellscape/webpack-plugin-serve#livereload instead for CSS.

Yeah I tried that. It works, but it kinda defeats the point of hot reloading... 😝

> I'm not sure (but I don't think) that webpack supports HMR for CSS.

It doesn't seem like it, at least not without plugins. I guess I've just been a bit spoiled by Parcel, so I'm trying to fill in some of the gaps in my dev workflow on a new project that I'm being "forced" to use Webpack on.

Anyway, thanks for the quick feedback!

P.S. Not sure if you've used Parcel before, but it has [no-config HMR](https://parceljs.org/hmr.html) that works out of the box for JS, CSS, React, Vue, you name it. It's freaking bliss.

**Comment by PlayMa256** [comment]
Yes, webpack (specially mini-css-extract-plugin) does not support it (according to them yet).
