### ISSUE TITLE
Support for opening specific url path

### ISSUE THREAD

**Issue by ahamid** [shellscape/webpack-plugin-serve#170]
### Feature Use Case

Open browser to specific static file path

### Feature Proposal

Documentation leads one to believe the [`open`](https://github.com/sindresorhus/open#options) option `url` might be used to set the full url to open, but this does not actually work, only the root is opened:
```javascript
new WebpackPluginServe({
	static: [outputPath, path.resolve('.')],
	open: {
		url: 'http://127.0.0.1:55555/path/to/page.html'
	}
})
```
I suspect this is an issue with the `open` api, target argument overriding any `url` option.
The equivalent `webpack-dev-server` option was `openPage` I believe:
```javascript
devServer: {
	open: true,
	openPage: 'path/to/page.html'
}
```

**Comment by bebraw** [comment]
Have you seen https://github.com/shellscape/webpack-plugin-serve/blob/master/recipes/open-custom-uri.md ?

I guess the question is, can we do what you proposed within the plugin itself? Likely the custom uri recipe exists for a reason.

**Comment by shellscape** [comment]
@bebraw is correct. that recipe exists to provide direction on opening a custom URI.
