### ISSUE TITLE
LiveReload error

### ISSUE THREAD

**Issue by felixcatto** [shellscape/webpack-plugin-serve#179]
Hi, thanks for a nice plugin. I have noticed a little error when liveReload option enabled.

- Webpack Version: 4.43.0
- Operating System (or Browser): Ubuntu, Chrome
- Node Version: v12.18.2
- webpack-plugin-serve Version: 1.0.1

### How Do We Reproduce?

Set `liveReload: true`, then reload browser window 11+ times manually by clicking F5 or indirectly by changing `index.js`. I described it here
https://github.com/felixcatto/WPS_error

### Expected Behavior

No errors in console

### Actual Behavior

I got a follwing error
![alt text](https://i.imgur.com/So4JfM1.png '?')

But liveReload continues to work as it should

**Comment by bebraw** [comment]
I can confirm this.

Usually this means there's a memory leak somewhere. The question is, is it something in the plugin or on webpack side.

**Comment by shellscape** [comment]
I toyed with this and I don't believe this to be the fault of this plugin. The reproduction in the OP was taken down so I'm going to close as abandoned.
