### ISSUE TITLE
HTTP2 with HMR is not documented

### ISSUE THREAD

**Issue by illusionalsagacity** [shellscape/webpack-plugin-serve#183]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

When using the HTTP2 dev server, the websocket HMR connection does not work by default, without enabling the `allowHTTP1` option.

### Your Proposal for Changes

Add a note to HMR and the HTTP2 readme sections that if using them together, `allowHTTP1` is required.

**Comment by shellscape** [comment]
Thanks for the issue. Happy to review a PR that adds this to the docs.
