### ISSUE TITLE
Watch mode doesn't work for a second instance

### ISSUE THREAD

**Issue by RuslanKim** [shellscape/webpack-plugin-serve#185]
- Webpack Version: 4.42.0
- Operating System (or Browser): Win10/Chrome
- Node Version: v12.18.3
- webpack-plugin-serve Version: 3.2.0

### How Do We Reproduce?
My webpack project has two instances for consumer part and admin console part:
webpack-serve --config ClientApp/conf/dev.config.js --host localhost --port 8070 --static ./wwwroot --wait-for-build --no-hmr
webpack-serve --config ClientApp/conf/dev-admin.config.js --host localhost --port 8071 --static ./wwwroot --wait-for-build --no-hmr

It can be reproduced on any project. The issue is watch and compile source changes does not work for second or other instances...
I have used to use webpack-dev-server and to solve this issue I had used --watch-poll option...
Unfortunately, this workaround does not help for webpack-serve.
What option should I use to solve this annoying issue?
Besides, even more, second instance finally ruin the 1st instance, completely :(

### Expected Behavior
Each instances should watch changes individually and should compile it as soon as possible...

### Actual Behavior
Watching sources and compile for 1st instance works perfectly but 2d or 3d does not work..

**Comment by shellscape** [comment]
Put together a minimal reproduction repo or we won't be able to triage your issue.

**Comment by RuslanKim** [comment]
> Put together a minimal reproduction repo or we won't be able to triage your issue.

even if it is reproduces on any project build?

**Comment by shellscape** [comment]
Alternatively you can provide a PR with a failing test.

**Comment by RuslanKim** [comment]
minimal reproduction repo 
https://github.com/RuslanKim/webpack-ts-polymer-example

>npm run dev

change  ClientApp\components\example-app\example-app.ts
static get template() { return html([`<style include=""></style><p>example app 123</p>`]) }

and change  
ClientApp\components-admin\example-admin\example-admin.ts

Then see whether these changes has been compiled for both projects... but now the issue is that second has stuck

**Comment by RuslanKim** [comment]
Oh sorry, I have change repo, please use latest commit (cc98663d23b0a37).

**Comment by shellscape** [comment]
@PlayMa256 do you have a moment to take a look at this?

**Comment by shellscape** [comment]
@RuslanKim that's nowhere near a minimal reproduction. Please read https://git.io/fNzHA for instructions on creating a minimal reproduction. We simply don't have the time to go through your entire app to find configs and other bits. Please make it simple so we can help you.

**Comment by PlayMa256** [comment]
@RuslanKim can you add a package.json with the scritps and dependencies you are using? I could not find them!

**Comment by shellscape** [comment]
@PlayMa256 sorry, I was too quick on asking you to step in. The reproduction repo needs to be distilled further before we can look at it.

**Comment by RuslanKim** [comment]
> @RuslanKim can you add a package.json with the scripts and dependencies you are using? I could not find them!
> 
> @shellscape sure!

Oh, my bad :(. Didn't notice  that packages are absent ... sorry. I have checked in them, please follow upper instruction. And `npm install` is required for sure...

**Comment by RuslanKim** [comment]
> @RuslanKim that's nowhere near a minimal reproduction. Please read https://git.io/fNzHA for instructions on creating a minimal reproduction. We simply don't have the time to go through your entire app to find configs and other bits. Please make it simple so we can help you.

does package.json helps? or it is still not near reproducable?

**Comment by shellscape** [comment]
@RuslanKim please read the link I provided to understand what a minimal reproduction is.

**Comment by RuslanKim** [comment]
> @RuslanKim please read the link I provided to understand what a minimal reproduction is.

It does not make sense... 
I need you help with your woundfull plugin exactly with my experinced sutuation ... you'd like to much isolated issue... I suppose you are interested in your plugin working well.
