### ISSUE TITLE
1.2.0 - Regression in historyFallback type

### ISSUE THREAD

**Issue by bebraw** [shellscape/webpack-plugin-serve#190]
- Webpack Version:
- Operating System (or Browser):
- Node Version:
- webpack-plugin-serve Version: 1.2.0

### How Do We Reproduce?

```js
const config = {
  plugins: [
    new WebpackPluginServe({
      historyFallback: undefined
    }),
  ]
}
```

**Demo:** https://runkit.com/bebraw/5f981a7f72191a001a75f313

### Expected Behavior

When `historyFallback` is set to `undefined`, webpack runs.

### Actual Behavior

Now it's crashing. Before 1.2.0 it didn't crash and I imagine `undefined` was coerced as `false`.

**Comment by shellscape** [comment]
Can you elaborate on "webpack runs"?

**Comment by shellscape** [comment]
@bebraw what's the error message/stack?

**Comment by bebraw** [comment]
It's a validation error from superstruct. Let me set up a standalone example so it's clearer.

**Comment by bebraw** [comment]
I added a minimal example at https://runkit.com/bebraw/5f981a7f72191a001a75f313 (change the version to 1.1.0 or 1.2.0). At least this shows the differing error. In 1.1.0 it's compiling without a validation error though it's crashing otherwise due to the environment.

**Comment by shellscape** [comment]
OK so it's in the move to superstruct then. I won't have time to fix this today, I'll be on the road. Can you or @TrySound update the superstruct config to fix this?

**Comment by bebraw** [comment]
@shellscape I guess the question is, should the behavior be the same for any field accepting a boolean? There are a couple of those.

**Comment by TrySound** [comment]
I guess before all fields were nullable. Now they are optional. Does it make sense to use undefined instead of default value?

**Comment by bebraw** [comment]
> I guess before all fields were nullable. Now they are optional. Does it make sense to use undefined instead of default value?

Maybe the thing to do would be to match the older, loose behavior for now, yeah. We can still do a stricter API in webpack-plugin-serve v2 and drop the loose handling if we feel that's better.

**Comment by shellscape** [comment]
Food for thought: https://github.com/shellscape/webpack-plugin-serve#historyfallback and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-plugin-serve/index.d.ts#L38. Technically, passing `undefined` and getting an error isn't a regression. The docs spell out that it's invalid, and the TS types match. So superstruct's current config is actually adhering to the docs, and passing `undefined` is an error.

Given that, I don't think we should change anything.

**Comment by bebraw** [comment]
Ah, yeah. I see what you are saying. I actually fixed the TS types to match the docs.

Let's keep it as it is then and mark this as `wontfix`.
