### ISSUE TITLE
Breaking change in 1.2.0: no longer possible to pass port as string

### ISSUE THREAD

**Issue by smashercosmo** [shellscape/webpack-plugin-serve#193]
Seems like since 1.2.0 it's no longer possible to set port as string

### How Do We Reproduce?

```js
new Serve({
  port: '3000',
  host: 'localhost',
})
```

### Expected Behavior
No errors

### Actual Behavior
```sh
⬢ wps: An option was passed to WebpackPluginServe that is not valid
/Users/smashercosmo/Documents/projects/backstage/portals/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^
```

**Comment by shellscape** [comment]
We updated the validation library we were using for options. Unfortunately you were making use of a technical bug, as the docs have always stated a number or promise type for that option: https://github.com/shellscape/webpack-plugin-serve#port

this is one of those updates that is in the gray area of whether or not it's breaking. a lot of folks were passing in invalid option values that the previous validator was letting slide through, even though it should not have. so technically, folks were relying on a bug and not a feature. apologies for any inconveniences this caused, but we did carefully consider these kinds of situations before releasing.

**Comment by smashercosmo** [comment]
Alright, thx for explanation

**Comment by blikblum** [comment]
Just hit this issue. IMO the only real problem is the missing info of what option was invalid.

**Comment by shellscape** [comment]
Hm is should list that. It's possible that webpack-cli is swallowing the error.

**Comment by blikblum** [comment]
I use webpack nano: get: " An option was passed to WebpackPluginServe that is not valid"

Used port as number and fixed.

Having "port option is incorrect" message would help to fix that

**Comment by shellscape** [comment]
Agreed. I'll look into it.
