### ISSUE TITLE
Add webpack 5 support

### ISSUE THREAD

**Issue by otakustay** [shellscape/webpack-plugin-serve#195]
### Feature Use Case

This plugin seems compatible to webpack 5, however npm 7 require exact peer dependencies match, since [@pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) has a peer dependent on it, it may affect all react-refresh users upgrading to npm 7.

### Feature Proposal

Add webpack 5.x to peer dependency.

**Comment by shellscape** [comment]
We're waiting for Webpack 5 to stabilize before making that change, but we will make it. There are too many critical bugs still open in their repo.

**Comment by shellscape** [comment]
Since this is active in the minds of myself and the folks who curate this package, and that it was recommended in the Survive JS book just recently along Webpack 5, please rest assured that we're going to add support officially when the time is right.

**Comment by jesec** [comment]
I second this. This plugin works perfectly fine so far with Webpack 5.x. 

```
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.20.2" from webpack-plugin-serve@1.2.1
```

npm 7 now mandates matching peer dependencies. Both npm 7 and Webpack 5 are now generally available. It does not hurt to simply accept Webpack 5.x as a valid peer dependency.

**Comment by TrySound** [comment]
Well, npm will be hated forever for this change.

**Comment by BenBeattieHood** [comment]
Just checking in on this, as it's been a few months - would you be willing to merge these changes in soon, or are there a specific set of issues on webpack 5 that you're waiting for resolution on?
