### ISSUE TITLE
How to inspect server?

### ISSUE THREAD

**Issue by Zummer** [shellscape/webpack-plugin-serve#196]
How to inspect server?

like: node inspect server.js

**Comment by shellscape** [comment]
Not familiar with that, and our issue templates are required.

**Comment by Zummer** [comment]
ok, how can i debug the server middleware, put breakpoints in google chrome inspector?

```
$ node inspect index.js
< Debugger listening on ws://127.0.0.1:9229/5adb6217-0757-4761-95a2-6af0955d7d25
< For help, see: https://nodejs.org/en/docs/inspector
```

**Comment by PlayMa256** [comment]
if you run `node --inspect` or `node --inspect-brk ./node_modules/.bin/webpack` can probably give you some idea... you can put debugger statements on your middleware to make it stop there

**Comment by Zummer** [comment]
ok, thanks

**Comment by Zummer** [comment]
yes, it works

**Comment by Zummer** [comment]
yes, it works
