### ISSUE TITLE
How reload serve?

### ISSUE THREAD

**Issue by Zummer** [shellscape/webpack-plugin-serve#197]
How reload serve?

For example when I change in middleware below 'Hello world' to 'Hello world_2' hot reload not work. No reload works at all.

```
module.exports = {
  plugins: [
    new WebpackPluginServe({
      middleware: (app, builtins) =>
        app.use(async (ctx, next) => {
          ctx.body = 'Hello world';
          await next();
        })
    })
  ]
};
```

**Comment by PlayMa256** [comment]
It spins off a server when webpack spins the process. Since this is heavily tied to the webpack process, we would have to kill it in order to restart. In other words, you cant reload the server without killing the webpack process!
