### ISSUE TITLE
Changing title of powershell terminal window

### ISSUE THREAD

**Issue by thunderkid** [shellscape/webpack-plugin-serve#201]
- Webpack Version: 4.44.1
- Operating System (or Browser): Windows 10 2020H2
- Node Version: 10.19.0
- webpack-plugin-serve Version: 1.2.0

### How Do We Reproduce?

I have powershell scripts that open multiple powershell terminal windows and run `webpack` with `webpack-plugin-serve` from within those windows. Prior to running `webpack`, my scripts first change the window titles to reflect the project being built in that window. I'm now finding that `webpack-plugin-serve` changes the title back to `Windows PowerShell`. This started occurring in version `1.1.0` - up to version  `1.0.1` everything worked fine. Aside from aesthetics, this is a problem because I have other scripts that open and close windows based upon their titles.

I believe this problem is due to a dependency of `webpack-plugin-serve`. After upgrading to version `1.2.0` and noticing this issue, I first tried to roll back using `npm install webpack-plugin-serve@1.0.1`, but found that the problem persisted. However, using `npm ci` caused the problem to go away.

My config is 
```    
    host:"localhost",
    port: 9000 + env.appNum * 10,
    progress: true,
    status: true,
    static: resolve(_qdir, './out/dist'), 
    liveReload: true,
    open: true,
    historyFallback: {
        //disableDotRule: true,
        rewrites: [
            {
                from: '/thingy/*',
                to: '/'
            }
        ]
        }
    };
```

### Expected Behavior
webpack-plugin-serve should not change the title of the terminal window.

### Actual Behavior
webpack-plugin-serve changes the title of the terminal window to `Windows PowerShell`

**Comment by shellscape** [comment]
Thanks for taking the time to open an issue.

I'm really not sure that this plugin is responsible for changing the window title. I can attest that we've got no code in the plugin that manually attempts to change a terminal window title (on any platform). So this looks like the edgiest of all edge cases. If you can pinpoint a specific cause and want to open a PR to adjust the plugin for your use case, I'd be happy to review a PR. For the time being, this is going to be a `wontfix`.

**Comment by thunderkid** [comment]
Fair enough - I expected that this would be totally unimportant for most users. I'll look through the code but if I can't see anything obvious I'll just hope that some upstream dependency fix magically makes the problem go away at some point.

Thanks for the plugin!
