### ISSUE TITLE
wps: Change in unaccepted module(s)

### ISSUE THREAD

**Issue by boojum** [shellscape/webpack-plugin-serve#205]
- Webpack Version: 5.9.0
- Operating System (or Browser): latest stable Chrome / Firefox on linux
- Node Version: 15.5.0
- webpack-plugin-serve Version: 1.2.1

### How Do We Reproduce?
- clone the minimal [example](https://github.com/boojum/react-base): `git clone https://github.com/boojum/react-base`
- install dependencies `npm --legacy-peer-deps i -D`
- run `npm start`
- open example page at [http://[::]:55555](http://[::]:55555)
- open your browser dev-tools console
- make a change to `src/app.jsx` and save
- observe the messages in the dev-tools console

### Expected Behavior
After changes to `src/app.jsx` the browser's tab will hot-reload its content.

### Actual Behavior
Output from Chrome Dev-Tools console:

```js
hmr.js:19 ⬡ wps: Change in unaccepted module(s):
 {type: "unaccepted", chain: Array(2), moduleId: "./src/index.jsx"}
onUnaccepted @ hmr.js:19
applyHandler @ main.js:967
(anonymous) @ main.js:669
internalApply @ main.js:668
hotApply @ main.js:660
replace @ hmr.js:65
async function (async)
replace @ hmr.js:52
eval @ client.js:70
hmr.js:20 ⬡ wps: {type: "unaccepted", chain: Array(2), moduleId: "./src/index.jsx"}
onUnaccepted @ hmr.js:20
applyHandler @ main.js:967
(anonymous) @ main.js:669
internalApply @ main.js:668
hotApply @ main.js:660
replace @ hmr.js:65
async function (async)
replace @ hmr.js:52
eval @ client.js:70
main.js:969 Uncaught (in promise) Error: Aborted because ./src/app.jsx is not accepted
Update propagation: ./src/app.jsx -> ./src/index.jsx
    at applyHandler (main.js:969)
    at main.js:669
    at Array.map (<anonymous>)
    at internalApply (main.js:668)
    at hotApply (main.js:660)
    at replace (hmr.js:65)
```

**Comment by shellscape** [comment]
You haven't instructed react to assign anything as HMR acceptable. See our React recipe here: https://github.com/shellscape/webpack-plugin-serve/tree/master/recipes/react

Please read through the documentation before creating new tickets.
