### ISSUE TITLE
webpack-plugin-serve - npm 7 pulls webpack 4

### ISSUE THREAD

**Issue by bebraw** [shellscape/webpack-plugin-serve#216]
### Expected Behavior / Situation

As npm 7 changed its default behavior for peer dependencies (it installs them!) and given the plugin works with webpack 5 as well, it might make sense to extend the peer dependency range to include webpack 5. Otherwise using the plugin with npm 7 may lead to confusion as the users may have to force npm to run in legacy mode.

### Actual Behavior / Situation

Now installing the plugin under npm 7 will pull webpack 4 which isn't expected for webpack 5 users.

### Modification Proposal

Include webpack 5 to peer dependency range.

**Comment by ankurk91** [comment]
Need to fix this line

https://github.com/shellscape/webpack-plugin-serve/blob/master/package.json#L38

**Comment by shellscape** [comment]
Closed by #226
