### ISSUE TITLE
HMR js chunk file request use wrong filename

### ISSUE THREAD

**Issue by AsukaSong** [shellscape/webpack-plugin-serve#219]
- Webpack Version: 5.24.4
- Operating System (or Browser): Chrome Version 88.0.4324.182 (Official Build) (x86_64)
- Node Version: v15.6.0
- webpack-plugin-serve Version: 1.3.0

### How Do We Reproduce?
`package.json`

```json
{
  "scripts": {
    "start": "wp"
  },
  "devDependencies": {
    "html-webpack-plugin": "^5.3.1",
    "webpack": "^5.24.4",
    "webpack-plugin-serve": "^1.3.0",
    "webpack-nano": "^1.1.1"
  }
}
```

`webpack.config.js`

```javascript
const Serve = require('webpack-plugin-serve').WebpackPluginServe
const HTML = require('html-webpack-plugin')

module.exports = {
  entry: ['./index.js', 'webpack-plugin-serve/client'],

  mode: 'development',

  watch: true,

  plugins: [
    new Serve({
      hmr: true,
      static: './dist'
    }),

    new HTML() // for render
  ]
}

```

`index.js`

```javascript
console.log('test')
```

- `yarn start`
- make some change on `index.js`

### Expected Behavior

- hmr success

### Actual Behavior

- `main-[hash]-main-wps-hmr.js` generated in `./dist`
- browser requests `_-[hash]-main-wps-hmr.js`, which failed with 404

### Maybe Reason

`webpack.output.hotUpdateChunkFilename` does not support `[runtime]` in filename template, then `[runtime]` fallback to `_`

https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js#L283

https://github.com/webpack/webpack/blob/master/lib/runtime/GetChunkFilenameRuntimeModule.js#L229

https://github.com/shellscape/webpack-plugin-serve/blob/master/lib/plugins/hmr.js#L28

```
hotUpdateChunkFilename:
      webpackMajorVersion >= 5
        ? `[runtime]-${compiler.wpsId}-[id]-wps-hmr.js`
        : `${compiler.wpsId}-[id]-wps-hmr.js`,
```

**Comment by chuyik** [comment]
related pr: https://github.com/shellscape/webpack-plugin-serve/pull/214

**Comment by AsukaSong** [comment]
> related pr: #214

that's awesome, waiting for merge and release

**Comment by shellscape** [comment]
> Webpack Version: 5.24.4

Thanks for reporting. We currently do not support Webpack v5. If that PR solves the problem, that's great! However I won't be supporting v5 at the moment, it's just not mature enough yet.
