### ISSUE TITLE
Please release new version with `client.protocol` support

### ISSUE THREAD

**Issue by pappasam** [shellscape/webpack-plugin-serve#221]
The current master contains some useful feature that haven't been released. I would really appreciate if we were able to release these features, and I imagine @shellscape might be the only individual with this kind of power.

### Feature Use Case

I would like to `npm install`, from npm, a version of webpack-plugin-serve with the feature merged in <https://github.com/shellscape/webpack-plugin-serve/pull/218>

### Feature Proposal

Please release a new version incorporating the recent `client.protocol` updates to master.

**Comment by pappasam** [comment]
Amazing, thank you so much for handling so quickly! And sorry for what may be a silly question: would you help me find the release that enabled us to close the issue? Was it published to a platform other than npm? And are we no longer using GitHub releases?

**Comment by shellscape** [comment]
package maintainer is released new versions when they are able to. we all have lives outside of GitHub

**Comment by pappasam** [comment]
Ahhhh, so we DIDN'T actually release anything. Sorry, normally when an issue is closed, I assume it's been resolved. I see that's not the case, I'm so sorry for wasting our time

**Comment by shellscape** [comment]
Ridiculously passive aggressive. Kindly go away
