### ISSUE TITLE
default port should no longer be 55555

### ISSUE THREAD

**Issue by ayyjohn** [shellscape/webpack-plugin-serve#222]
### Expected Behavior / Situation

`webpack-serve` should just work without config on macos

### Actual Behavior / Situation

port 55555 is now in use on macos big sur by default (which many devs use)
https://developer.apple.com/forums/thread/671197
had to add 

```javascript
const { WebpackPluginServe: Serve } = require('webpack-plugin-serve');
...
module.exports = {
...
  plugins: [new Serve({
    port: 8000
   })],
...
};
```

to my `webpack.config.js`

otherwise without it I get

```
⬢ webpack: Error: listen EADDRINUSE: address already in use :::55555
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at WebpackPluginServe.start (/Users/ayyjohn/code/project/node_modules/webpack-plugin-serve/lib/server.js:86:10) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 55555
}

```
### Modification Proposal

choose a new default port

**Comment by shellscape** [comment]
Thanks for the issue. That's super unfortunate. The good news is that the documentation is clear as to what the default port is for this package, and there's an easy workaround. 55555 has been unused by default for well over a decade by vendors and it's unfortunate that Apple has decided to buck that trend, but I don't feel it's worth cutting a new major release at this time.

**Comment by ayyjohn** [comment]
Entirely fair. Thanks for the response!

Out of curiosity, when I add the above snippet to `webpack.config.js`
I get the following warning

```
⬢ wps: Duplicate instances created. Only the first instance of this plugin will be active.
⬡ webpack: Watching Files
⬡ wps: Server Listening on: http://[::]:8000
```
Is this expected because I'm creating a new `Serve` instance, and is there a way to do it without triggering the warning? I want to make sure I'm doing it right. I followed https://github.com/shellscape/webpack-plugin-serve/blob/master/recipes/dynamic-port.md but without dynamically fetching the port.
