### ISSUE TITLE
Connecting to the client at a remote URL

### ISSUE THREAD

**Issue by rafpaf** [shellscape/webpack-plugin-serve#227]
I'm developing remotely, so I need webpack-plugin-serve to connect to a URL like `ws://dev.example.com/wps`. The plugin is still attempting to connect at `ws://localhost:9000/wps`, even though I have set the client option to `{ protocol: "ws", address: "147.147.147.147:9000" }`.

In my `webpack.config.js`, the options are as follows. (These aren't my actual IP address and host, of course.) 

```js
      new Serve({
        port: 9000,
        client: { protocol: "ws", address: "147.147.147.147:9000" },
        host: "dev.assets.example.com",
        compress: true,
        hmr: true,
        static: "./dist",
      }),
```

**Comment by shellscape** [comment]
Sounds like you're reporting a bug, in which case you should open a bug issue or submit a PR to fix.

**Comment by rafpaf** [comment]
I've opened a bug report here: https://github.com/shellscape/webpack-plugin-serve/issues/228.
