### ISSUE TITLE
Incremental build is broken in latest webpack

### ISSUE THREAD

**Issue by serkanyersen** [shellscape/webpack-plugin-serve#231]
I upgraded to the latest version of webpack `5.64.1` and incremental builds started to run for all files instead of only the changed ones.

I drilled it down to this section.

https://github.com/shellscape/webpack-plugin-serve/blob/ba83bf5b041604cd7e20f22470ca52be10491060/lib/index.js#L260-L264

Somehow applying the `DefinePlugin` is invalidating all files in watch mode and everything gets rebuilt.

**Comment by shellscape** [comment]
Issue templates are not optional in this repo

**Comment by serkanyersen** [comment]
I think this is a bug/missing feature on github

<img width="708" alt="Screen Shot 2021-11-18 at 12 39 37 PM" src="https://user-images.githubusercontent.com/30582/142493240-63e5c344-c2a0-4913-8eb6-bcf1c6816c7f.png">
I created the issue like this, which then bypasses all issue guidelines or message templates. it's not my intention to deliberately skip the issue templates.

**Comment by shellscape** [comment]
Good to know. I'll take a look at that and see what I can do to mitigate this again. Thanks for letting me know.
