### ISSUE TITLE
incremental builds are broken on the latest version of webpack.

### ISSUE THREAD

**Issue by serkanyersen** [shellscape/webpack-plugin-serve#232]
I upgraded to the latest version of webpack `5.64.1` and incremental builds started to run for all files instead of only the changed ones.

I drilled it down to this section.

https://github.com/shellscape/webpack-plugin-serve/blob/ba83bf5b041604cd7e20f22470ca52be10491060/lib/index.js#L260-L264

Somehow applying the `DefinePlugin` is invalidating all files in watch mode and everything gets rebuilt.

- Webpack Version: 5.64.1
- Operating System (or Browser): macos Big Sur 11.6 (20G165)
- Node Version: 16
- webpack-plugin-serve Version: 1.4.1

### How Do We Reproduce?

- upgrade to latest webpack
- start dev build in watch mode
- make a change in any file

### Expected Behavior
- only the changed files get rebuilt

### Actual Behavior
- everything gets rebuilt

**Comment by PeterKottas** [comment]
I am seeing the same thing. As a side note, I am also seeing a warning:
```
WARNING in DefinePlugin
Conflicting values for 'ʎɐɹɔosǝʌɹǝs'
```
plus the HMR or live reload is no longer working.

**Comment by shellscape** [comment]
@PeterKottas "me too" is a meaningless reply. if you have new symptoms or side effects, open a new issue with a new repro. otherwise use the reaction buttons so you don't spam the issue's subscribers.

**Comment by shellscape** [comment]
@serkanyersen 

> Issues without minimal reproductions will be closed! Please provide one by:
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions). These may take more time to triage than the other options.

**Comment by PeterKottas** [comment]
@shellscape hence I've added the warning I was seeing. I have also mentioned the HMR is broken, possibly as a result of the warning. Btw, closing legit issues just because there's no minimum repo might not be the best way to approach things. Just my 2 cents.

**Comment by shellscape** [comment]
@PeterKottas follow the rules or don't play. I manage enough repos, for long enough to know what works and what doesn't. Take a cue from folks with vastly more experience. Your inexperience is showing as you've disregarded my comment about opening a new issue for new symptoms.
