### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by PeterKottas** [shellscape/webpack-plugin-serve#234]
I've noticed a lack of activity in the repo, I was just wondering if I should start looking for an alternative. Info much appreciated, thanks!

**Comment by matheus1lva** [comment]
Of course it is. A repo not being updated != not alive. We have being going from ups and downs but we are still going strong!

**Comment by shellscape** [comment]
Use vite.

**Comment by PeterKottas** [comment]
Thanks for the info @matheus1lva, hope you'll find some more time to merge PRs and look at issues in the future. All the best. @shellscape I hear loud and clear, vite looks interesting but I think our setup is way too intertwined with webpack, I'll see if I can get things done with the standard webpack dev server. Things might have gotten better there.

**Comment by shellscape** [comment]
😂 webpack-dev-server is a huge step down. vite also works fine with webpack. honestly I think you'd serve yourself by slowing down and learning a bit more about the tech you're trying to use.
