### ISSUE TITLE
Invalid arguments: hostname must be a string or falsey

### ISSUE THREAD

**Issue by TrySound** [shellscape/webpack-plugin-serve#38]
- Webpack Version: 4.26.1
- Operating System (or Browser): mac os x
- Node Version: 10.14.0
- webpack-plugin-dev Version: 0.1.1

### How Do We Reproduce?

```
    new WebpackPluginServe({
      host: '0.0.0.0',
      historyFallback: true,
      static: path.join(__dirname, 'public'),
    }),
```

### Expected Behavior
No errors

### Actual Behavior

```
⬡ webpack: Watching Files
[HPM] Proxy created: reqPath => ...
⬢ webpack: TypeError: Invalid arguments: hostname must be a string or falsey
    at Object.lookup (dns.js:130:11)
    at lookupAndListen (net.js:1500:7)
    at Server.listen (net.js:1476:7)
    at WebpackPluginServe.start (/Users/.../node_modules/webpack-plugin-serve/lib/server.js:77:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:72755) ExperimentalWarning: The http2 module is an experimental API.
error Command failed with exit code 1.
```

**Comment by TrySound** [comment]
Log shows that passed to createServer host is a function

**Comment by shellscape** [comment]
Thanks for the heads up. That's awfully strange, I'm running nearly an identical options set with no error. @PlayMa256 can you take a look at this? I'm away for a few hours.

**Comment by Morgul** [comment]
@TrySound I just ran into this myself. I got around it by commenting out `host: '0.0.0.0'`.

I'm on macOS and node 10.11.0.

**Comment by shellscape** [comment]
One of us will get this resolved today :+1:

**Comment by shellscape** [comment]
@TrySound patch is up on NPM

**Comment by TrySound** [comment]
Great thank you
