### ISSUE TITLE
Support attempting automatic reconnection

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#42]
### Feature Use Case

When I restart the server to apply new changes, I currently have to refresh the page manually; this means having to change focus from my IDE to my browser, which is annoying when fiddling with the development servers configuration.

### Feature Proposal

The client makes a series of attempts to reconnect via websocket to the development server, over a period of intervals, before giving up.

This is a feature currently done by `webpack-dev-middleware`. While it's not the nicest thing to have, as it results in unavoidable console spam (as most browsers log failed ws connection attempts as security messages, meaning they're not visible nor surpressable by JS), I feel it's a justifiable enough feature, since the console is usually cleared on page reloading anyway.

**Comment by shellscape** [comment]
I agree this is an important nice-to-have. There are multiple scripts in the plugin that make use of a WebSocket (progress, minimal progress, status dialog, core client script) and any other consumers could potentially do the same by injecting their own clients and listening for events.

We'll have to do this intelligently so multiple sockets can make use of this.
