### ISSUE TITLE
Comparison to webpack-dev-server

### ISSUE THREAD

**Issue by joeljeske** [shellscape/webpack-plugin-serve#48]
Thanks for your work, I love seeing competing solutions that mix up a space. Can you please provide a comparison to webpack-dev-server? What are your value props over the existing solution?

**Comment by shellscape** [comment]
I think this post does a good job of explaining the differences: [Plugin to a Fresh Webpack Development Serve](http://shellscape.org/2018/11/27/webpack-plugin-serve) (also on [medium](https://medium.com/@shellscape/plugin-to-a-fresh-webpack-development-server-a8d4b859aa78)). The _Decidedly Different_ section is probably what you're looking for.

Aside from that, I personally like to avoid direct and specific comparisons. It often doesn't serve much purpose and creates a weird environment. There is the [`feat/benchmarks`](https://github.com/shellscape/webpack-plugin-serve/tree/feat/benchmark) branch that has some empirical data on speeds etc.

You may notice that this solution is faster on the whole, as there are a lot less moving parts. Comparing the options between the two, you'll find that many are available, and many are omitted. As the post describes, this plugin is ultimately much more flexible than the other two available development servers.

**Comment by shellscape** [comment]
Please see #52. We'll be merging that soon, and it gives you a full-scope of feature parity and differences between the dev servers.
