### ISSUE TITLE
FAQ - leak comparison

### ISSUE THREAD

**Issue by rosskevin** [shellscape/webpack-plugin-serve#53]
I read the medium post and docs listed here: https://github.com/shellscape/webpack-plugin-serve/issues/48

Regarding the leaks in webpack-dev-server https://github.com/webpack/webpack/issues/6929, is this plugin taking a different approach than webpack-dev-server with HMR or should I expect the same leaks due to upstream dependencies?

Any impetus for me to switch at this point is:
1. memory leak/crash (both with storybook and our app's webpack.config) - really painful
2. any speed improvements

Do I have any hope looking here for a resolution?

**Comment by shellscape** [comment]
Thanks for opening this one.

> memory leak/crash (both with storybook and our app's webpack.config) - really painful

So the one big differentiating factor here is that we _don't_ use webpack-dev-middleware, and both webpack-dev-server and webpack-serve do. webpack-dev-middleware creates an in-memory filesystem to handle the flood of HMR-related JSON and JS files, so the user doesn't have those dumping to filesystem constantly. We've mitigated that problem and have no need for the MemoryFileSystem nor the other moving parts of webpack-dev-middleware. All that means that out of the box, running this plugin for a dev server should result in less memory usage on the whole, every time.

So far in testing, we haven't run into any memory-related crashes. Now, as you know from posting that issue, webpack itself has some really leaky pipes. This plugin can't do much about those, just as the other dev server options are beholden to that. 

> any speed improvements

The `feat/benchmarks` branch contains a WIP benchmarks suite that @PlayMa256 has been working on. Testing how the webpack internals run on different platforms (this module versus webpack-dev-server for example) have been problematic. But I can state with confidence that you'll notice _some_ speed differences/improvement in the experience using this plugin, as our infrastructure around the webpack internals is much better (imho). 

> Do I have any hope looking here for a resolution?

I would think so. There's a ton of overhead that the other alternatives have that this plugin doesn't. Give it a shot, and if you need a hand, let us know.

**Comment by PlayMa256** [comment]
Also if you have any feedbacks on how we could improve our benchmark suite, let us know. We are currently looking a way to measure hmr performance, which is hard.
