### ISSUE TITLE
html-webpack-plugin fails with serve plugin

### ISSUE THREAD

**Issue by TrySound** [shellscape/webpack-plugin-serve#55]
- Webpack Version: the latest
- Operating System (or Browser): mac os sierra
- Node Version: v8.12.0
- webpack-plugin-serve Version: 0.2.1

### How Do We Reproduce?

https://github.com/TrySound/wp-bug

**Comment by pronevich** [comment]
Just now got the same bug with identical error log

**Comment by shellscape** [comment]
We're taking a look at it. It's a pretty obscure error so it might take some time to narrow down the cause.

**Comment by shellscape** [comment]
OK so html-webpack-plugin's error reporting is woefully inadequate, but we managed to manually log the webpack errors that were being thrown, and narrowed it down to this line in our plugin: https://github.com/shellscape/webpack-plugin-serve/blob/b81d8bccf851860596f1285db0ed21f8311ca22d/lib/hmr-plugin.js#L63

We'll try to get a fix in for this as soon as possible.

**Comment by pronevich** [comment]
I will notice that v0.1 works fine

**Comment by shellscape** [comment]
Yeah 0.1 didn't have all of the changes for MultiCompiler support integrated.

**Comment by pronevich** [comment]
@shellscape build and server start working, app was started and then after I change some code - all breaks:

```
/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36
        if (asset.sourceAndMap) {
                  ^

TypeError: Cannot read property 'sourceAndMap' of undefined
    at getTaskForFile (/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36:12)
    at files.forEach (/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval [as call] (eval at create (/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:14:1)
    at SyncHook.lazyCompileHook (/project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/project/node_modules/webpack/lib/Compilation.js:1313:42)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (/project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/project/node_modules/webpack/lib/Compilation.js:1309:36)
error Command failed with exit code 1.
```

**Comment by yyccQQu** [comment]
Html Webpack Plugin:
  Error: webpack:///(webpack)/buildin/harmony-module.js?:39
  /* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./harmony-module.js */ "./node_modules/webpack/buildin/harmony-module.js")(modul  e)))
                                                                                                                                            ^
  TypeError: __webpack_require__(...) is not a function
  
  
  - index.html:2778 Module../node_modules/webpack/buildin/harmony-module.js
    /Users/saoshuai/newbee/provue/index.html:2778:1
  
  - index.html:684 __webpack_require__
    /Users/saoshuai/newbee/provue/index.html:684:30
  
  - index.html:61 fn
    /Users/saoshuai/newbee/provue/index.html:61:20
  
  
  - index.html:2766 Module../node_modules/webpack/buildin/global.js
    /Users/saoshuai/newbee/provue/index.html:2766:1
  
  - index.html:684 __webpack_require__
    /Users/saoshuai/newbee/provue/index.html:684:30
  
  - index.html:61 fn
    /Users/saoshuai/newbee/provue/index.html:61:20
  
  - lodash.js?:17101 eval
    [.]/[lodash]/lodash.js?:17101:41
  
  - index.html:2754 Object../node_modules/lodash/lodash.js
    /Users/saoshuai/newbee/provue/index.html:2754:1
Please help me !!!!!! Thank you very much~~~~

**Comment by yyccQQu** [comment]
can I use  v0.1 html-webpack-plugin?

**Comment by PlayMa256** [comment]
@yyccQQu depends on the version of webpack you are using. We currently support webpack 4.28.1 and i suppose html-webpack-plugin v0.1 is not compatible with webpack 4. That must be a problem with this incompatibility.
