### ISSUE TITLE
Error on page reload

### ISSUE THREAD

**Issue by TrySound** [shellscape/webpack-plugin-serve#59]
- Webpack Version: 4.27.1
- Operating System (or Browser): mac os sierra
- Node Version: 8.12
- webpack-plugin-serve Version: 0.2.2

### How Do We Reproduce?

- start this project https://github.com/TrySound/wp-bug
- enable preserve log option in devtools
- reload the page

### Expected Behavior

Not error on reload

### Actual Behavior

![image](https://user-images.githubusercontent.com/5635476/50032973-b3a1b080-0007-11e9-9116-58d37a205437.png)

**Comment by shellscape** [comment]
👍 This was a side effect of our reconnect feature. I'll have a fix up later tonight. It's safe to disregard this error message in the mean time.

**Comment by pronevich** [comment]
@shellscape I have this error on reloading in wps log:

```
Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
```

**Comment by shellscape** [comment]
@pronevich see #61 :smile:

**Comment by TrySound** [comment]
Could you publish patch release with this?

**Comment by chuyik** [comment]
![image](https://user-images.githubusercontent.com/6262943/103134819-f74b4c80-46ee-11eb-8ab8-35355c58f4c7.png)
I also see this error on every page reload.

Tested version: 1.2.0 and 1.2.1
