### ISSUE TITLE
Allow users to specify a page to open after build is complete

### ISSUE THREAD

**Issue by KyleW** [shellscape/webpack-plugin-serve#64]
### Feature Use Case

For some idiosyncratic reasons, I'd like my browser to open 'http://[::]:5555/#/local' after the build is complete instead of 'http://[::]:5555'. However, open.target isn't currently supported in the config.

### Feature Proposal
Allow users to specify a custom path to open once build is complete. The value should probably live at config.open.target and gets passed onto opn in lib/server.js:100

**Comment by shellscape** [comment]
Thanks for opening an issue.

> However, open.target isn't currently supported in the config.

Are you seeing an error with regard to this? Per the README, `open` is passed through to the underlying dependency, `opn`. So you should be able to use any of the options for that module in that options property.

Our validation schema defines a boolean or object for that value as well: https://github.com/shellscape/webpack-plugin-serve/blob/54f2870f6cb76c105afb0f69a64707cfb8e6c4f8/lib/validate.js#L23

If you have more information, please do share it.

**Comment by PlayMa256** [comment]
Opn does not support target on its config and by default `opn` as it is set right now will open:  
```js
const uri = `${protocol}://${url.format(this.options.address)}`;
```
I guess we can do a workaround where `open.target` is possible and if present it replaces `uri` on the opn call.

**Comment by shellscape** [comment]
Ah, that's right. `target` is a hard parameter. The solution then is to use events:

```js
const open = require('opn');
const { WebpackPluginServe } = require('webpack-plugin-serve');

const serve = new WebpackPluginServe(...options...);

serve.on('listening', () => {
  opn(customUrl);
});

// ... the rest of the webpack config
```
