### ISSUE TITLE
Compile files in-memory, not in dist of workdir

### ISSUE THREAD

**Issue by pronevich** [shellscape/webpack-plugin-serve#65]
### Expected Behavior / Situation
In development mode, all that I need is a server which somehow gives me good DX for work on the project. Don't see any benefits of dist folder in project root in dev mode.

### Actual Behavior / Situation
Now wps create dist folder at the project root. Many projects using this folder for their production builds, I think this creates some confuse.

### Modification Proposal
Keep dev builds in-memory or hidden folder that should destroy after each server stop.

**Comment by shellscape** [comment]
That's something that this project will never do. I hate to use such absolute terms, but it is the truth. This plugin makes no such assumptions about what the user wants. Rather, the user should configure their build to their needs. This plugin does not control output details - webpack controls that - how it should be.

webpack-dev-server and webpack-serve both use webpack-dev-middleware, which does in-memory builds, and causes an insane amount of trouble for users. Memory usage issues, unpredictability, buggy MemoryFileSystem - the list goes on. If you'd like in-memory compilation, you'll have to use a project which leverages webpack-dev-middleware.

Alternatively, you can set your build output to a system temporary directory.

**Comment by pronevich** [comment]
It was not immediately clear to me, now I got it, that should work with the output throw webpack as is.

**Comment by jquense** [comment]
It would be really nice to have an option to plug the webpack filesystem like the others do with memory-fs. I've not ever personally had any problems with the dev server behavior and not having in memory builds is a deal breaker for us.

Please support what you feel is best of course, just wanted to add a voice on the other side that this is a very important features for some folks

**Comment by shellscape** [comment]
@jquense thanks for weighing in. Unfortunately this isn't something we're going to support directly in the plugin, as there is simply no need. I've never seen a good, techincal reason for using memory-fs, and there are enough alternatives out there which support it.

One thing you're missing though, is that the plugin _doesnt have to_. This is just a plugin! WPS isn't some overbearing, opinionated goliath. You're still free to do whatever you want to with the compiler and the config. See for example this use of memory-fs: 3513c2fe859e11e1d04428a21b27c6dd
