### ISSUE TITLE
Absolute position wps-status

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#67]
### Expected Behavior / Situation
Build warnings & errors are visible on top of page content.

### Actual Behavior / Situation
Build warnings & errors are pushed to the bottom of the page, when there is a large amount of content on the page, and in some cases even hidden (when things like modals are open).

### Modification Proposal

Currently the `wps-status` overlay sits inline with the rest of the page. This means it can be pushed around by the rest of the page, which can result (in particular) in it pushed out of sight.

It would make sense for the overlay to be absolutely positioned, so that it 'hovers' above the entire page. This is usually how build status overlays are done in the other webpack build tools, and (I think) makes sense given that you can minimise the overlay, and `wps-status-beacon` is already absolutely positioned.

**Comment by shellscape** [comment]
Thanks for the report. Would welcome a PR for this fix 😄

**Comment by G-Rath** [comment]
I'll give it a go when I have the time, but can't promise nothing as my css skills are somewhat lacking 😆

(Relatively speaking of course 😜)
