### ISSUE TITLE
Enable node 11 support?

### ISSUE THREAD

**Issue by pearofducks** [shellscape/webpack-plugin-serve#73]
### Expected Behavior / Situation

Support for node 11 in `engines`.

Per [this comment](https://github.com/nodejs/node/issues/24958#issuecomment-446270196) from the related node regression (as mentioned in the FAQ), it seems node 11 shouldn't be affected.

### Actual Behavior / Situation

Node 11 not supported, so yarn users unable to use without `--ignore-engines` (which causes headaches that are yarn's fault).

### Modification Proposal

```
  "engines": {
    "node": ">= 8.0.0 < 9.0.0 || >= 10.0.0 < 10.14.0 || >= 11.0.0"
  },
```

(Add `>= 11.0.0` to `engines`)

**Comment by PlayMa256** [comment]
Hello, thank you for the input. We will do some tests on 11.x versions to see if everything is safe or don't have any regressions because the same problems we had with 10.14 were applied to a version on the 11.x, I just need to find out which was. 

As far as i see there are no bad implications on that, but this has to also be discussed with other maintainers as well.

**Comment by shellscape** [comment]
This is dicey. Odd-numbered versions are only around for 6 months, and greatly increase the maintenance burden. They often contain experimental features which may or may not transition to stable features, and which often cause other headaches. (Node 9 had a ton of memory management issues). There's also the matter that we really only want to support two major versions at a time, and those which are in Active LTS. Odd-numbered majors aren't in LTS, and don't have any sort of LTS after their 6-month lifecycle. Node used to publish odd-numbers as unstable, but I can't seem to track down documentation of that any longer, nor can I track down documentation on odd-numbered versions _not_ being unstable. Blogs about this can't seem to reach consensus either.

I've reached out to some folks on Twitter for clarification, but I'd like to be able to reference something of an authority before pulling the trigger on the change, given the afore mentioned burden this would add.

**Comment by pearofducks** [comment]
I completely understand! My only suggestion would be to maybe consider standardizing support across projects. Both this and _webpack-nano_ share a similar 'evergreen' branding/disclaimer, but _webpack-nano_ supports node 10+ for engines.
