### ISSUE TITLE
Allow resolution of .html files when no extension is requested

### ISSUE THREAD

**Issue by mindpivot** [shellscape/webpack-plugin-serve#80]
### Feature Use Case
Client-side rendered apps break when file extensions such as .html are present on the URL. I would like to be able to request a route, `/account/test` for example, and have webpack-plugin-serve resolve to `/account/test.html` (if the corresponding html file is present) without changing the URL on the client (i.e. no redirect). It seems the included koa-static middleware allows for this through an options setting 'extensions', which is an array of file extensions to be resolved by koa. I believe the pattern looks like this:

`{ extensions: [ '.html', '.htm'] }`

(honestly, it's unclear to me if the leading period is needed)

### Feature Proposal
Please allow for requesting routes without file-extensions which successfully resolve to matching filenames containing specified extensions (or even allowing the behavior for .html files by default). Ideally, this would happen without altering the URL on the client.

**Example:**
a `/dist` directory has been specified as a static path to resolve from site-root, all files are contained within that directory. within that directory is another directory named `account`. within the `account` directory is a file named `test.html`.

Browser requests: `/account/test`
webpack-plugin-serve finds file: `/account/test.html`
WPS returns the contents of the .html file at route `/account/test`.

Perhaps the most straightforward way to allow for this would be to provide a place to pass options into koa-static along with filesystem paths to resolve?

Thank you!

**Comment by shellscape** [comment]
@mindpivot would this kind of an implementation work for you:

```js
// webpack.config.js
module.exports = {
  plugins: [
    new WebpackPluginServe({
      middleware: (app, builtins) =>
        const koaStaticOpts = { ... };
        builtins.static([ ...paths... ], koaStaticOpts);
    })
  ]
};
```

The `koaStaticOpts` would get applied to every static path defined in the `[ ...paths... ]` array.

**Comment by mindpivot** [comment]
That would work great! I actually tried that exact configuration in my webpack.config.js file based on the koa-static docs.

**Comment by shellscape** [comment]
Life happened. I will do my best to get this change in as soon as possible.

**Comment by mindpivot** [comment]
Sorry it took a while to get around to this. I've made the configuration change to my webpack config and can confirm it works beautifully. Thanks!!
