### ISSUE TITLE
Ensure wps-status indicators are always top z-index on page

### ISSUE THREAD

**Issue by mindpivot** [shellscape/webpack-plugin-serve#81]
### Feature Use Case
Current problem: Using WPS on a legacy codebase where I'm switching the build over from gulp. Legacy codebase has styles I cannot safely alter without triggering full-scale regression testing. If the z-index is too high on an element (the top-nav in my case), the wps-status indicator is hidden from view.

See attached animated gif.
![wps-progress-indicator](https://user-images.githubusercontent.com/1554893/50656634-e1707a00-0f61-11e9-8534-aa197074de9d.gif)

### Feature Proposal
One of two options come to mind:

Setting the z-index of the WPS progress widget(s) to the max allowed z-index of 2147483647 ([StackOverflow answer on max z-index](https://stackoverflow.com/questions/491052/minimum-and-maximum-value-of-z-index))

**OR**

Dynamically find highest z-index on the page post-render and add 1 to that number for the progress widget(s). ([Find highest z-index](https://www.willmaster.com/blog/javascript/z-index-range.php))

**Comment by shellscape** [comment]
:+1: we've talked about doing exactly that (the max value) with both progress and status dialogs.
