### ISSUE TITLE
running multiple instances at the same time

### ISSUE THREAD

**Issue by floriansimon1** [shellscape/webpack-plugin-serve#85]
Hi,

I have a question. My use case:

We have a webapp that has end-to-end tests performed via Selenium. We often want to run two instances of Webpack: one for development, one for end-to-end tests, with different bundles. I can run them in parallel on two different ports, but I face the issue that whatever instance is launched last ends up serving its own bundle on both ports for some reason.

Am I clear enough? If so, is it something you're aware of?

**Comment by shellscape** [comment]
I would need to see your setup and configuration to be certain, but it sounds like the bundle for the last instance is being written to the same filesystem location as the first instance. If that proves to be the case, I would recommend using a flag (if you're using `webpack-nano` you can choose whichever flag you want) to specify which is which, and where the build output for a particular instance should be written to.

One thing that this plugin does differently than webpack-dev-server and webpack-server is that it does not rely on webpack-dev-middleware; webpack-dev-middleware keeps build files in memory. That ultimately ends up causing more problems than it solves, especially for large builds.

**Comment by floriansimon1** [comment]
Thanks a lot, that's the kind of answer I was expecting! I don't think there's anything wrong with the plugin, so I'm just gonna close this.

That was fast!

**Comment by shellscape** [comment]
No problem. Here to help!
