### ISSUE TITLE
Bundles are rebuilt on every load when using "production" mode

### ISSUE THREAD

**Issue by EvHaus** [shellscape/webpack-plugin-serve#89]
- Webpack Version: 4.28.4
- Operating System (or Browser): MacOS 10.14.3
- Node Version: v11.6.0
- webpack-plugin-serve Version: 0.4.0

### How Do We Reproduce?

When I try to use `webpack-plugin-serve` with `"mode": "production"` in my webpack config, I'm seeing a strange behavior. Everytime I refresh my page in the browser, webpack rebuilds the entire production build before it gets served. This means that refreshing the page takes several seconds (in my case).

When using `"mode": "development"` this doesn't seem to happen (or it happens so fast that I can't notice this anymore).

### Expected Behavior

The files should be built once, and the re-served on every page refresh.

### Actual Behavior

Everytime I refresh the page, webpack rebuilds my entire bundle set making reloads extremely slow.

**Comment by PlayMa256** [comment]
Hi, i used the react recipe as a test and i was not able to reproduce. Can you provide a reproduction example?

**Comment by shellscape** [comment]
Agreed. We're going to need exact steps or a minimal reproduction preferably in a separate repo we can access. (The issue template outlines that need as well) Without it, it's quite impossible to know your setup or what may be causing this.

**Comment by EvHaus** [comment]
I've created a repro test case with a GIF illustrating the steps here: https://github.com/shellscape/webpack-plugin-serve/pull/91

Hopefully that helps.

**Comment by EvHaus** [comment]
Closing this. Turns out this was a result of behavior inside [`webpack` itself](https://github.com/webpack/webpack/issues/7007). When you use `watch` with `production` module enabled, it doesn't cache anything so if builds go into your static directory it will consider that a change and trigger a rebuild.

**Comment by shellscape** [comment]
That's a great find @EvHaus. Well done.
